= Managing compliance with the Enterprise Contract

The Enterprise Contract (EC) is an artifact verifier and customizable policy checker. By default, {ProductName} adds the Enterprise Contract as an integration test to each new application. The Enterprise Contract then keeps your software supply chain secure and ensures container images comply with your organization's policies. It does this by verifying the security and provenance of builds created through {ProductName}.

{ProductName}'s build process uses Tekton Chains to produce a signed in-toto provenance attestation of the build pipeline. The Enterprise Contract then uses this attestation to verify the build's integrity and compliance with a set of policies. These policies include best practices and any organization-specific requirements.

If you ever need to restore the default EC integration test to an application, or if you want to use a different configuration of the EC as an integration test, see our xref:/testing/integration/adding.adoc[Adding an integration test] guide.

.Additional resources
* To produce a signed link:https://in-toto.io/in-toto/[in-toto] attestation of the build pipeline, go to link:https://tekton.dev/docs/chains/[Tekton Chains].
* For information on the source code for the Tekton pipelines defined in the bundle, see the link:https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/enterprise-contract.yaml[build-definitions] and
link:https://github.com/enterprise-contract/ec-cli/blob/main/tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml[ec-cli] repositories.
* To use a specific version of the pipeline bundle instead of the devel tag, you can select one of the link:https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-enterprise-contract?tab=tags[pinned tags].
* For information on the Enterprise Contract policies designed for {ProductName}, see the link:https://enterprisecontract.dev/docs/ec-policies/index.html[Enterprise Contract Policies].
