= Inspecting artifact SBOMs

A software bill of materials (SBOM) provides greater transparency for your software supply chain. {ProductName} provides link:https://www.cisa.gov/sites/default/files/2023-04/sbom-types-document-508c.pdf[build SBOMs], which list all the software libraries that a component uses. Those libraries can enable specific functionality or facilitate development. 

You can use an SBOM to better understand the composition of your software. In particular, you can use various tools to scan your SBOM and determine if any of your dependencies have known vulnerabilities. Furthermore, to comply with cybersecurity regulations, your organization might need to provide its customers with the SBOM for your application's components. For example, in the United States, the link:https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/[Executive Order on Improving the Nation's Cybersecurity] requires vendors to provide SBOMs, and in Europe, the link:https://www.cisa.gov/sites/default/files/2023-09/EU%20Commission%20SBOM%20Work_508c.pdf[Cyber Resilience Act] does the same.

== Viewing an SBOM in the web UI

.Prerequisites

* You must have a component that {ProductName} has successfully built.

.Procedure

In the console, complete the following steps to download the SBOM for a component:

. Navigate to the *Activity* > *Pipeline runs* tab.

. For the component whose SBOM you want to view, select its most recent pipeline run.

. On the *Pipeline run details* page, select *View SBOM*. 
.. You can use your web browser to immediately search the SBOM for terms that indicate vulnerabilities in your software supply chain. For example, try searching for "log4j".
.. You can select *Download* to download the SBOM, or *Expand* to view it full-screen.

[NOTE]
====
The SBOM is unsigned so there is no way to verify whether it has been tampered with after being pushed to the registry. Additional integrity verification should be performed before distributing the artifact if needed.
====

== Downloading an SBOM in the CLI

.Prerequisites

* Install the link:https://docs.sigstore.dev/cosign/installation/[Cosign] CLI tool.

* Install the link:https://stedolan.github.io/jq/download/[jq] CLI tool.

* xref:/getting-started/cli.adoc[Login] to {ProductName}.

* You have found the image for a xref:/building/creating.adoc#finding-the-built-image[recently completed build pipeline] and exported the value to the `IMAGE` environment variable.

.Procedure

In the CLI, complete the following steps to download the SBOM for a component:

. Use Cosign to download the SBOM. Pass the IMAGE environment variable as an argument into Cosign's `download sbom` command.

+
.Example
+
[source]
----
$ cosign download sbom $IMAGE
----

+
.. (Optional) To view the full SBOM in a searchable format, you can redirect the output:

+
[source]
----  
$ cosign download sbom $IMAGE > sbom.txt
----

== Reading the SBOM
In the SBOM, as the following sample excerpt shows, you can see four characteristics of each library that a component uses:

. Its author or publisher
. Its name
. Its version
. Its licenses

This information helps you verify that individual libraries are safely-sourced, updated, and compliant. 

[source]
----
{
    "bomFormat": "CycloneDX",
    "specVersion": "1.4",
    "serialNumber": "urn:uuid:89146fc4-342f-496b-9cc9-07a6a1554220",
    "version": 1,
    "metadata": {
        ...
    },
    "components": [
        {
            "bom-ref": "pkg:pypi/flask@2.1.0?package-id=d6ad7ed5aac04a8",
            "type": "library",
            "author": "Armin Ronacher <armin.ronacher@active-4.com>", <1>
            "name": "Flask", <2>
            "version": "2.1.0", <3>
            "licenses": [ <4>
                {
                    "license": {
                        "id": "BSD-3-Clause"
                    }
                }
            ],
            "cpe": "cpe:2.3:a:armin-ronacher:python-Flask:2.1.0:*:*:*:*:*:*:*",
            "purl": "pkg:pypi/Flask@2.1.0",
            "properties": [
                {
                    "name": "syft:package:foundBy",
                    "value": "python-package-cataloger"
                    ...
----
