= Getting started with {ProductName}

Adopting new platforms is always challenging. While we aim to make use of industry standard terminology and
processes, sometimes we will need to introduce additional concepts. More definitions can be found in the
xref:glossary:index.adoc[glossary].

== Key concepts

=== Namespace
In Kubernetes,
link:https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/[namespaces]
provide a foundational mechanism for isolating groups of resources within a
single cluster. All of the {ProductName} resources and APIs that you interact
with are scoped to namespaces, including your Components, Applications, Snapshots,
Secrets and the Tekton PipelineRuns that perform builds, tests, and releases.

==== Tenant namespace
These are namespaces where artifacts are produced from Tekton Pipelines. These can be accessed by more than one
individual according to their roles and the permissions defined by 
link:https://konflux-ci.dev/architecture/ADR/0011-roles-and-permissions.html[those roles]. The tenant namespaces can be either
for an individual or a team.
//TODO: Document the process for getting access to/creating new namespaces

In {ProductName}, you operate in a tenant namespace which is scoped to your
team. One team can span multiple namespaces if needed, each with many
applications with components. Namespaces should NOT be shared by many teams.

In your tenant namespace, you will xref:building:creating.adoc[create
Components and Applications], run the xref:building:index.adoc[build
PipelineRuns] that are defined in your git repositories, view and iterate on
the xref:testing:index.adoc[results of your IntegrationTestScenarios], and
xref:releasing:index.adoc[create Releases] to release specific Snapshots
according to specific ReleasePlans.

==== Managed namespace
These are namespaces where a managed environment team manages release pipelines
and credentials for your organization.

The primary interaction mode between tenant and managed namespaces is to create
a Release in a tenant namespace referencing a specific Snapshot which will
trigger a specific release pipeline in the managed namespace. See
xref:releasing:index.adoc[release documentation] for more.

=== Custom Resource (CR)
In Kubernetes, a
link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom
Resources (CR)] is an extension of the Kubernetes API.

All {ProductName} APIs are implemented as Kubernetes CRs. If
you're familiar with common Kubernetes resources such as Pods and Deployments,
you'll find that {ProductName} resources appear on cluster in the same way:
Applications, Components, Snapshots, and PipelineRuns.

A consequence of this fact is that commonplace Kubernetes client tools such as
link:https://kubernetes.io/docs/reference/kubectl/[kubectl] understand and can
work with {ProductName} APIs.

==== Component
A Component CR describes the properties for an OCI artifact including the git repository where the artifact is from,
its latest built commit, initial build configuration parameters, and any relationships to
other Components. The CR also contains a reference to its single owning Application.
Component names are unique in a namespace, even when components are used in different application.

===== Build pipeline
When you create a Component in {ProductName}, a build pipeline is pushed to the git repository in the `.tekton/`
directory and a webhook is installed.

Upon a new push or pull request (merge request in GitLab) event, the pipeline defined in the repository is
run. This pipeline describes the process to build and test a specific artifact. The build process includes Tekton
Tasks such as cloning the git repository, prefetching dependencies, building the OCI artifact and source SBOM, and
generating the source container. The test process includes Tekton Tasks such as running Snyk scans, checking for
CVEs with clair-in-ci, and running an antivirus scan on the artifact.

{ProductName} inherits the pattern of defining Tekton build pipelines in git
from its use of https://pipelinesascode.com/[Pipelines as Code (PaC)]. PaC
enables the use of a Tekton PipelineDefinition within a git repository and for
that pipeline to be triggered upon new commits and PRs to the repository.

Artifacts that you build in your tenant namespace are pushed to an OCI registry
along with their supporting metadata (including xref:metadata:index.adoc[SLSA provenance attestations and SBOMs]).

=== Application
An Application CR owns multiple Components. It helps to logically group Components in the UI.

When a new Component's build pipeline is complete, a new Snapshot is created by the
Integration Service containing the latest git and OCI reference from each of the Component CRs plus the just-produced
Component artifact. This is used as the input to an IntegrationTestScenario.

==== Snapshot
A Snapshot CR is an immutable set of Component references. It can be created from push or pull request events.
A Snapshot defines a set of Components which are either tested or released together.

Over time as you produce more builds, your tenant namespace will have many
Snapshots in it. Understand that at any point in time, a given
Snapshot _might not necessarily_ represent the latest built artifacts for all
Components in your tenant namespace.

==== IntegrationTestScenario
An IntegrationTestScenario (ITS) CR is a Tekton Pipeline defining a test which is intended to run against an
entire Snapshot. The Integration Service runs all ITSs which are configured for the Snapshot's Application. A
default ITS is automatically created for every new Application to enable all Components to be checked against
a specified EnterpriseContractPolicy.

Each ITS can be configured as optional for release. All non-optional tests must pass before the new Component
build is "promoted" to update the references on the Component CR.

==== EnterpriseContractPolicy
Building in {ProductName} follows a "build once, release multiple times" mentality where each release can have
separate requirements on the builds before allowing the action. These build requirements are codified in an
EnterpriseContractPolicy (ECP).

When an ECP is evaluated against a Snapshot, a single result is returned according to the highest violation. If,
for example, all Components pass the policy requirements, the policy evaluation is true. If a single
Component in a Snapshot fails the policy, however, the overall result is a failure even if all of the rest have
clean passes.

==== ReleasePlan
A ReleasePlan (RP) CR maps an Application you want to release with a release action.
It defines the process to release future Snapshots of your Application in the managed namespace. It also defines
whether or not you have automatic releases enabled and additional data to be supplied to each release
pipeline that runs in the future.

==== ReleasePlanAdmission
You also need to create a ReleasePlanAdmission (RPA) CR in the managed namespace. It defines the specific pipeline to
run and a given ECP which needs to pass for any Snapshot before that pipeline can proceed. It also defines important
details about the delivery of your content that we want to exercise some control over. For example, if your release pipeline uses an
link:https://github.com/konflux-ci/release-service-catalog/blob/production/tasks/managed/apply-mapping/apply-mapping.yaml[apply-mapping]
task, the `.spec.data.mapping.components` section of this resource will define which destination repositories your
content is pushed to.

==== Release
Every time you want to release newly built artifacts, you will create a Release CR in *your* tenant namespace. The Release
CR represents your intent to release some content to customers. It is an active resource that, when present, will
initiate the push of content.

A Release CR references a specific Snapshot and ReleasePlan. It indicates your intention to ship the content
in the Snapshot by way of the referenced ReleasePlan.

NOTE: It is possible to configure your ReleasePlan with xref:releasing:create-release-plan.adoc[auto-release].
When enabled, the {ProductName} system will generate your Releases for you whenever your Snapshots pass all of their
IntegrationTestScenarios.

NOTE: https://issues.redhat.com/browse/KONFLUX-1364[Future functionality], will allow you to
automatically collect dynamic metadata for inclusion in the autogenerated Release CRs.

include::partial${context}-additional-getting-started.adoc[]

== Getting started with the CLI

include::partial${context}-getting-started-with-the-cli.adoc[]
