= RPM lockfiles

== Introduction

MintMaker offers a custom extension on top of https://docs.renovatebot.com/[Renovate], that allows the automatic updates
of RPM lockfiles through the https://github.com/konflux-ci/rpm-lockfile-prototype[rpm-lockfile-prototype] project.

This extension is enabled by default for all repositories without any additional
Renovate configuration.

== Implementation

The RPM lockfiles are different from the typical approach seen in many programming languages.
Unlike in `pyproject.toml` or `package.json`, there is no way to pin dependencies (RPMs) to specific versions or ranges. The input file (`rpms.in.yaml`) describes
how the RPMs are resolved and how the lockfile is generated.
The lockfile (`rpms.lock.yaml`) contains a snapshot of the RPMs installed in
your container image, however, these are always the *latest* versions available
in the repositories. Once the repositories are updated to newer versions, the
lockfile is not consistent anymore and needs to be updated.

In MintMaker, all RPM updates are grouped into a single PR/MR. This is because
the lockfile implementation doesn't allow for single dependency updates
and it needs to be refreshed as a whole every time.


Please find how to generate RPM lockfile in xref:ROOT:building:prefetching-dependencies.adoc#rpm[documentation for enabling RPM prefetching].

== How MintMaker detects RPM lockfiles

MintMaker searches the repository for files named `rpms.in.yaml`/`rpms.in.yml` and assumes that a lockfile named `rpms.lock.yaml`/`rpms.lock.yml` exists in that same directory. MintMaker supports multiple lockfiles in a repository, but they must be placed in different directories.

== How to enable automerge for RPM security updates

It's possible to configure RPM security updates to automerge based on the severity of the fixed CVEs. To enable this functionality, add the following top-level setting to your renovate configuration:

[source,json]
----
{
  "rpmVulnerabilityAutomerge": "ALL" | "MEDIUM" | "HIGH" | "CRITICAL"
}
----
The setting can be set to one of these four values, and the security updates will be automerged if the severity of the fixed CVEs will be at least as high as the configured value. `ALL` will automerge every RPM security update. If this configuration option is not set, automerge is implicitly disabled.

== RPM lockfile with RPMs that require subscription

MintMaker is able to update RPM lockfiles containing RPMs that require subscription, but some setup needs to be completed first. Firstly, activation key secret needs to be added to the user namespace. This process is described in detail in the xref:ROOT:building:activation-keys-subscription.adoc[Using Red Hat activation keys to access subscription content] article. Secondly, the RPM repofile needs to be modified to make use of the custom authentication certificate and key. For each repository requiring authentication, please set `sslclientkey = $SSL_CLIENT_KEY` and `sslclientcert = $SSL_CLIENT_CERT`. This will ensure that MintMaker sets the correct paths for the authentication. For example:

[source]
----
[rhel-9-for-x86_64-baseos-rpms]
name = Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
baseurl = https://cdn.redhat.com/content/dist/rhel9/$releasever/x86_64/baseos/os
enabled = 1
gpgcheck = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
sslclientkey = $SSL_CLIENT_KEY
sslclientcert = $SSL_CLIENT_CERT
----

NOTE: After using variables like these in your repo config, you need to set
corresponding environment variables if you run the `rpm-lockfile-prototype`
script manually. These environment variables must be prefixed with `DNF_VAR_`.
For example, for the `SSL_CLIENT_KEY` variable, you should set an environment
variable named `DNF_VAR_SSL_CLIENT_KEY`.

== What to do if RPM security PRs don't contain any vulnerabilities

This behavior is caused by an upstream renovate bug, where the old renovate branch is reused in the creation of a new PR. Manually removing the renovate branch (for example `konflux/mintmaker/main/lock-file-maintenance-vulnerability`) in your git repository should resolve the issue. To prevent this issue from happening in the future, enable auto deletion of source branches in your repository. In GitLab, check the option `Enable "Delete source branch" option by default` in the `Merge requests` repository settings. For GitHub, follow https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches[these instructions].