= Creating a release plan admission

.*Prerequisites*

* An existing Development and Managed workspace.

* An existing `ReleasePlan` object in the Development workspace.

.*Procedures*

. Create a `ReleasePlanAdmission.yaml` object locally.

+
*Example `ReleasePlanAdmission.yaml` object*

+
[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
 name: sre-production <.>
 namespace: managed-workspace <.>
spec:
 applications:
  - demo-app <.>
 data: <key> <.>
 environment: <sre-production> <.>
 origin: <dev-workspace> <.>
 pipelineRef: <pipeline_ref> <.>
 policy: <policy> <.>
 serviceAccount: <service-account> <.>

----

+
<.> The name of the release plan admission.
<.> The Managed environment team's workspace.
<.> A list of applications that you want to enable to be deployed in the managed workspace.
<.> Optional: An unstructured key used for providing data for the managed Pipeline.
<.> Optional: The environment from which the application updates are allowed to be received in the Managed workspace. This environment is created by the Development team.
<.> The development team workspace where the application is defined.
<.> Reference to the Pipeline to be executed by the release service.
<.> The enterprise contract policy against which the system validates an application before releasing it to production.
<.> Optional: The name of the service account to use in the Pipeline to gain elevated privileges. It's used only if you have defined the `pipelineRef` value.

+
NOTE: The  ReleasePlanAdmission.yaml represents the reciprocal link to the ReleasePlan.yaml objects created by the development team.

. In the Managed workspace, apply the `ReleasePlanAdmission.yaml` file and add the resource to your cluster by running the following command:

+
[source,shell]
----
oc apply -f ReleasePlanAdmission.yaml -n managed
----

.*Verification*

. On the Trusted Application Pipeline console, select the *Release services* > *Release plan admission* tab.
. Review the Release plan admission object that you just added. Using the Release plan admission tab, you can update or delete the selected Release plan object.

 
== The `copy-application.sh` script

.*Prerequisites*

* An existing Development and Managed workspace.

* Download link:https://github.com/redhat-appstudio/release-service-utils/blob/main/copy-application.sh[./copy-application.sh] script.

.*Procedures*

* Run the following command to copy the application from the development workspace to the managed workspace:

+
[source,shell]
----
./copy-application.sh <managed workspace name> -a <development workspace name>/<application name>
----

+
To show the command usage information, run the `./copy-application.sh --help` command.
