= Tenant Release Pipelines

The usual release process in {ProductName} involves two different teams: a *Development team* and a *Managed environment team* as described in
xref:/advanced-how-tos/releasing/index.adoc[Releasing an application]. The development team is usually the one who develops and support the application while the managed team will control the process and the secrets. Although this is a powerful workflow, in some cases it might feel very limiting. For example, sometimes the Development team wants to release their software to some destination that is directly under their control, using their own secrets, without depending on a Managed environment team. Another example would be performing actions before running the managed pipeline such as cleaning up old images or notifying about an ongoing release. The way {ProductName} supports these scenarios is by using something we call a *tenant release pipeline*. It's a release pipeline that runs in the tenant namespace of the Development team, rather than in that of the Managed environment team.

The gist here is that this workflow doesn't require a managed pipeline. You can omit the `target` and just specify the `tenant pipeline` you want to run. But, if both tenant and managed pipelines are provided, the tenant pipeline needs to succeed before continuing with the release of the application.

== Using a tenant pipeline ==

Before starting to use a tenant pipeline there are some prerequisites you will have to fulfill:

* You have an existing Development workspace.
* You have completed the steps listed in the xref:/getting-started/cli.adoc[Getting started in the CLI] page.
* You have a ServiceAccount with Roles allowing you to consume Releases and Snapshots.
* You have access to a tenant pipeline.

To use a tenant pipeline:

. Follow the regular instruction to xref:/advanced-how-tos/releasing/create-release-plan.adoc[create a ReleasePlan] YAML file locally.
. Specify the details about the tenant pipeline to run using the `tenantPipeline` field.

+
*Example `ReleasePlan.yaml` object*

+
[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
  name: publish
  namespace: dev-workspace
spec:
  application: <application-name>
  data:
    mapping:
      components:
        - name: demo-component-1
          repository: registry/destination-image-repository-1
          tags: [latest]
        - name: demo-component-2
          repository: registry/destination-image-repository-2
          tags: [latest]
  target: managed-workspace
  tenantPipeline:
    pipelineRef: <.>
      resolver: git
      params:
        - name: url
          value: "https://github.com/<your-github-user>/<your-pipeline-repo>.git"
        - name: revision
          value: main
        - name: pathInRepo
          value: "<path-to-your-pipeline>"
    serviceAccountName: appstudio-pipeline <.>
----

+
<.> Reference to the tenant pipeline to be executed in the development workspace.
<.> The name of the service account used to execute the tenant pipeline.

. In case you want to avoid the execution of a managed pipeline, remove the `target` field from your `ReleasePlan.yaml` file.
. In the Development workspace, apply the `ReleasePlan.yaml` file and add the resource to your cluster by running the following command:

+
[source,shell]
----
kubectl apply -f ReleasePlan.yaml -n dev
----

. Provision any secrets needed by the particular release pipeline you chose and xref:/how-tos/configuring/creating-secrets.adoc[upload them to the Development workspace].

== Creating a new tenant pipeline ==

Tenant pipelines are Tekton pipelines defined by the {ProductName) community and are not supported by the release team. To fully integrate them with your workflow, you can define three optional parameters that, if defined, will be populated by the release service. Those parameters are `release`, `releasePlan` and `snapshot`. Each of this parameters will get the namespacedName reference to the resource so you can load them and process them in your pipeline.

*Example tenant pipeline*

[source,yaml]
----
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: my-tenant-pipeline
spec:
  params:
    - name: release <.>
      type: string
    - name: releasePlan <.>
      type: string
    - name: snapshot <.>
      type: string
  tasks:
    - name: echo-resources
      taskSpec:
       steps:
         - name: echo resources
           image: ubuntu:latest
           script: |
             #!/usr/bin/env sh
             echo "Release $(params.release)"
             echo "ReleasePlan $(params.releasePlan)"
             echo "Snapshot $(params.snapshot)"
----
<.> Namespacedname to the Release populated automatically by the release service (eg. dev-workspace/my-tenant-release).
<.> Namespacedname to the ReleasePlan populated automatically by the release service (eg. dev-workspace/publish).
<.> Namespacedname to the Snapshot populated automatically by the release service (eg. dev-workspace/my-snapshot).

If you write a good reusable release pipeline, please submit it to our link:https://github.com/konflux-ci/release-service-catalog[catalog] so others can use it.


== Next steps ==

Now that the ReleasePlan is defined, the development team can create a Release object to reference a specific Snapshot and the new ReleasePlan. It indicates the users' intent to release that Snapshot via the tenant release pipeline defined in the ReleasePlan.
