= Policy Evaluations

In {ProductName}, there are two places where Conforma Policies are used by default,
integration tests and release pipelines.

== Integration Tests

For integration tests, the Policy is defined in an IntegrationTestScenario resource. These are
stored in the same namespace as your Application. They are created automatically when a new
Application is created via the Web UI.

IntegrationTestScenarios have multiple purposes. Running EC validation is just one of them. As such,
you may have multiple of these resources in your namespace. The one that runs EC points to
`pipelines/enterprise-contract.yaml` Tekton Pipeline in the
`https://github.com/konflux-ci/build-definitions` repository.

More details
xref:testing:integration/editing.adoc#configuring-the-enterprise-contract-policy[here].

== Release

The release pipeline uses EC as a gating step. The `.spec.policy` attribute of the
ReleasePlanAdmission associated with your Application specifies which Policy is used during a
release.

More details xref:releasing:create-release-plan-admission.adoc[here].
