= Defining component relationships

When a tenant namespace includes multiple components, their repositories might contain references to image builds of another component. For example, an application might include multiple child components that, using a Dockerfile `FROM` clause, reference the image build of a common parent. Or, a component might reference image builds from another application altogether. OpenShift operators, for example, often have references to several components across applications.

In such instances, whenever you build a new image of the common parent component, you need to update the references to it. Specifically, you need to copy and paste the pullspec and image digest of that new image to your other source repositories. This process is tedious and error-prone.

However, if you build an application with {ProductName} and make references between components with image digests (`sha256:...`), {ProductName} can automatically generate pull requests to update those references. To use this functionality, simply define the relationships between your components, either in the {ProductName} UI, or in your CLI.

[CAUTION]
====
{ProductName} only updates image digest references. If images use tag references, these will not be updated.
====
[CAUTION]
====
If image digests are pointing to an architecture-specific link:https://github.com/opencontainers/image-spec/blob/main/manifest.md[Image Manifest], nudging will update the digest to a matching architecture. In order for nudging to update to the digest to an link:https://github.com/opencontainers/image-spec/blob/main/image-index.md[Image Index], the current digest needs to be pointing to an Image Index.
====

[NOTE]
====
By default, {ProductName} only looks for image digest references in Dockerfiles, Containerfiles, and YAML files. However, you can xref:./customizing-the-build.adoc[customize your build pipeline] to adjust that list of files with an annotation on the push PipelineRun definition. This annotation supports a comma-separated list of link:https://docs.renovatebot.com/string-pattern-matching/[regex or glob patterns]. The following annotation would replicate the default behavior.
====

[source,yaml]
----
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: ".*Dockerfile.*, .*.yaml, .*Containerfile.*"
----

== In the UI

.Procedure

To define the relationships between components in a tenant namespace, complete the following steps in the {ProductName} UI:

[NOTE]
====
Currently, applications with only one component do not have the option to define relationships in the UI. To achieve the same result for single-component applications, you can define the relationship in the CLI.
====


. Navigate to your application.
. On any tab, use the *Actions* drop-down menu to select *Define component relationships*.
.. Alternatively, go to the *Components* tab and select the *Define component relationships*.
. In the *Component relationships* window, select one component from the *Select a component* drop-down menu.
. Select *Nudges* or *Is nudged by*, depending on the relationship you want to define.

+
[NOTE]
====
Component A _nudges_ Component B (or Component B _is nudged by_ Component A) if Component B contains a reference, by image digest, to a build of Component A. After successful push builds of Component A, nudging updates the image digest that Component B references.
====

. Use the remaining drop-down menu to choose which other components belong to this relationship.
. To define multiple relationships, select *Add another component relationship*.
. Once you have defined all necessary relationships, select *Save relationships*.

.Verification

To verify the new relationship in the UI:
. Go to the *Components* tab for your application.
. Select a component that belongs to the relationship you defined.
. Scroll to the end of the page and select *Show related components*.

Alternatively, in the git repo for the component that nudges, push a commit. When the build for that component completes, you should see a new pull request appear for the component that is nudged. This new pull request contains the image digest for the new build of its parent image.


.Troubleshooting

* On any tab, use the *Actions* drop-down menu to select *Define component relationships*. If you do not see the relationship, try to define it again and then make sure to select *Save relationships*.
* Ensure that the existing references in the repositories of your components are correct.

== In the CLI

Prerequisites:

* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started in the CLI] page.

.Procedure

. In your CLI, xref:ROOT:getting-started.adoc#getting-started-with-the-cli[login] to {ProductName}.
. List your components, and identify the names of the components you want to relate to each other.
+
`kubectl get components`
+
[NOTE]
====
Component A _nudges_ Component B (or Component B _is nudged by_ Component A) if Component B contains a reference by image digest to a build of Component A. After successful push builds of Component A, nudging updates the image digest that Component B references.
====
. Patch the components to establish the nudging relationship.
+
`kubectl patch components/<name of component that nudges> -p '{"spec":{"build-nudges-ref": ["<name of component that is nudged>"]}}' --type=merge --kubeconfig=<path to kubeconfig>`

+
NOTE: You can also use **kubectl edit** to add the build-nudges-ref instead of patching the component.

.. You found the names of the two components in the last step.
.. The `kubeconfig` and its path are the same you used to login to {ProductName}.

.Verification

* Get the component custom resource (CR) definition for the components that nudges. The definition should include a line that says `build-nudges-ref:`, and beneath that, the name of the component that is nudged.
+
`kubectl get components/<name of component that nudges> -o yaml --kubeconfig=<path to kubeconfig> | less`
* Push a commit to the component that nudges. When the build completes, you should see a new pull request appear for the component that is nudged. This new pull request contains the image digest for the new build of the parent image.


.Troubleshooting

* Ensure that the existing references in the repositories of your components are correct.
* Try running the necessary commands again, and ensure you have the correct syntax.

== Customizing nudging PRs
Nudging feature is using renovate `https://docs.renovatebot.com/` to actually do the job,
for which you can customize some options specified in ConfigMap in your namespace.

Only following options are possible to customize via ConfigMap (for more details about those options refer to `https://docs.renovatebot.com/`.):

* automerge
* automergeType
* commitMessagePrefix
* commitMessageSuffix
* fileMatch (',' comma is separator)
* ignoreTests
* platformAutomerge
* gitLabIgnoreApprovals
* automergeSchedule (';' semicolon is separator)
* labels (',' comma is separator)


.There are two possible ways to customize:
. Create namespace wide config in ConfigMap named *`namespace-wide-nudging-renovate-config`* (*the name is mandatory*)
which will be used for all nudged components in your namespace, unless component specific config exists.
. Create config for specific nudged component in ConfigMap in your namespace and add annotation `build.appstudio.openshift.io/nudge_renovate_config_map` to the component with value of ConfigMap name and
it will be used for the component in your namespace.

Both ConfigMaps have the same format, where keys are allowed options in the list above, values
are always strings, so in case option is boolean, you will have to specify "true" or "false".

When you have either of ConfigMaps, nudging default renovate config will use additionally options from your ConfigMap.

.ConfigMap Example

[source,yaml]
--
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-wide-nudging-renovate-config
  namespace: <namespace>
data:
  automerge: "true"
  automergeType: "pr"
  commitMessagePrefix: "custom namespace prefix message"
  commitMessageSuffix: "custom namespace suffix message"
  fileMatch: ".*Dockerfile.*, .*.yaml, .*Containerfile.*"
  ignoreTests: "true"
  platformAutomerge: "true"
  gitLabIgnoreApprovals: "true"
  automergeSchedule: "* 22-23,0-4 * * *; * * * * 0,6"
  labels: "customLabel1, customLabel2"
--
