= Creating source control management secrets

Some source control providers require authentication secrets to enable {ProductName} to access your repositories. This guide explains how to create and configure SCM (Source Control Management) secrets for Pipeline-as-Code integration.

[IMPORTANT]
====
If you upload a GitHub access token to a tenant namespace, {ProductName} won't use the global GitHub application when accessing GitHub repositories.
====

== Prerequisites

* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started with the CLI] page.
* You have obtained an access token from your source control provider:
** xref:building:creating-gitlab.adoc#creating-a-gitlab-access-token-and-secret[GitLab access token guide]

== Creating a basic SCM host secret

Create a secret with your SCM access token by running the `kubectl create` command with a YAML file. This secret will apply to all repositories on the specified SCM host.

The secret must include the following labels:

* `appstudio.redhat.com/credentials: scm` - identifies this as an SCM credentials secret
* `appstudio.redhat.com/scm.host: <source-control-management-host>` - specifies the SCM host (e.g., `gitlab.com` or `github.com`)

[source,bash]
----
kubectl create -f scm-secret.yaml
----

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: pipelines-as-code-secret
  namespace: <YOUR NAMESPACE>
  labels:
    appstudio.redhat.com/credentials: scm
    appstudio.redhat.com/scm.host: <source-control-management-host> # for example, gitlab.com or github.com
type: kubernetes.io/basic-auth
stringData:
  password: <ACCESS TOKEN>
----

[NOTE]
====
Using the PAT (Personal Access Token) authentication requires only the `password` key. The `username` should not be set. If you set both the `username` and `password` keys, the authentication type will be considered as `basic`, and a basic authentication client will be created using those credentials. This client might not work or can be considered as a deprecated login method by some Source Code Management (SCM) providers.
====

This secret will be used by the build service to perform builds with Pipeline-as-Code.

== Adding multiple secrets with limited scope

This section extends the basic SCM host secret configuration described above. You can scope secrets to specific repositories or organizations by adding the `appstudio.redhat.com/scm.repository` annotation, allowing you to use different credentials for different organizations or repositories within the same namespace. You can also have multiple secrets with different labels and/or annotations.

=== Secret lookup mechanism

The secrets lookup mechanism searches for secrets in the following order, using the first match found:

. *Repository-specific secret* - a secret with the `appstudio.redhat.com/scm.repository` annotation matching the exact repository path
. *Organization-wide secret* - a secret with the `appstudio.redhat.com/scm.repository` annotation using a wildcard pattern (e.g., `my-org/*`)
. *Host-level secret* - a secret with only the `appstudio.redhat.com/scm.host` label matching the SCM host

=== Organization-wide secret

To create a secret for all repositories in an organization, add the `appstudio.redhat.com/scm.repository` annotation with a wildcard:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: pac-my-org-secret
  namespace: <YOUR NAMESPACE>
  labels:
    appstudio.redhat.com/credentials: scm
    appstudio.redhat.com/scm.host: <source-control-management-host>
  annotations:
    appstudio.redhat.com/scm.repository: my-org/*
type: kubernetes.io/basic-auth
stringData:
  password: <ACCESS TOKEN>
----

=== Repository-specific secret

To create a secret for a specific repository:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: pac-my-repo-secret
  namespace: <YOUR NAMESPACE>
  labels:
    appstudio.redhat.com/credentials: scm
    appstudio.redhat.com/scm.host: <source-control-management-host>
  annotations:
    appstudio.redhat.com/scm.repository: <repository-path> # for example, my-org/my-repo
type: kubernetes.io/basic-auth
stringData:
  password: <ACCESS TOKEN>
----

[NOTE]
====
You can have multiple repositories listed under the `appstudio.redhat.com/scm.repository` annotation. Separate repository names with commas when listing them. The secret will be used for all repositories that match the specified paths.
====

