= Onboarding a component from Forgejo with the CLI

Create components from Forgejo repositories using `kubectl`.

== Prerequisites

* xref:installing:enabling-builds.adoc[Enabled] build pipelines for your instance of {ProductName}.
* link:https://kubernetes.io/docs/tasks/tools/[kubectl] CLI tool
* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started with the CLI] page.
* An existing application in your namespace.

[[creating-a-forgejo-access-token-and-secret]]
== Creating a Forgejo access token and secret

Before onboarding a component from Forgejo, you must create a source control secret to enable {ProductName} to access your Forgejo repository.

.Procedure

. In Forgejo, navigate to User Settings.

. Click on *Applications* in the left menu.

. In the *Generate new token* section, name the new token as desired.

. In **Select permissions**, configure the following permissions:
+
* *issue*: Read and write
* *repository*: Read and write

. Click *Generate token*.

. Copy the generated token immediately, as it will be shown only once at the top of the screen.

. Create a secret in your {ProductName} tenant namespace. See xref:building:creating-scm-secrets.adoc[Creating source control management secrets] for detailed instructions on creating the secret with the token.

[IMPORTANT]
====
* Store the token securely after copying it, as you will not be able to view it again in Forgejo.

* The access token is scoped to the permissions you selected, so ensure you have granted sufficient permissions for {ProductName} to interact with your repository.
====

== Creating a component

. Create a `Component.yaml` file locally.

+
.Example `Component.yaml` object
include::partial$custom-resources/{context}-component-forgejo.adoc[]

+
NOTE: Request annotation 'build.appstudio.openshift.io/request' can be set also to 'configure-pac-no-mr' and
then during onboarding the onboarding PR won't be created and users will have to create pipeline run yaml
files for the component manually.

. Create an `ImageRepository.yaml` file locally.
+
.Example `ImageRepository.yaml` object
include::partial$custom-resources/{context}-imagerepository.adoc[]

. Apply the resource to your namespace by running the following command:

+
[source,shell]
----
$ kubectl apply -f Component.yaml ImageRepository.yaml
----

+
NOTE: You can create additional components by adding their custom resource configurations to the `Component.yaml` file. Separate multiple resources with `---`:
+
[source,yaml]
----
# Component A
---
# Component B
----

. Configure the build pipeline for your component:
.. If the annotation `build.appstudio.openshift.io/request: configure-pac` is set on the component, {ProductName} automatically creates a pull request in your repository with the Tekton pipeline definitions. Review and merge this pull request to complete the setup.
.. If the annotation is not set or is set to `configure-pac-no-mr`, manually create or update the Tekton pipeline files in your repository.

+
NOTE: The PipelineRun will run only for submitters who have permission to run PipelineRuns or who receive an `/ok-to-test` comment from an authorized user. +
For further details on PipelineRun permissions, please refer to the https://pipelinesascode.com/docs/guide/running/[PipelinesAsCode documentation].

. Once the pull request is made, a build pipeline should start. Track its progress in the {ProductName} UI or see the final status in Forgejo after the pipeline completes. If the pipeline is successful, merge the pull request.
