= Creating source control management secrets

Some source control providers require authentication secrets to enable {ProductName} to access your repositories. This guide explains how to create and configure SCM secrets for Pipeline-as-Code integration.

== Prerequisites

* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started with the CLI] page.
* You have obtained an access token from your source control provider:
** xref:building:creating-gitlab.adoc#creating-a-gitlab-access-token-and-secret[GitLab access token guide]

== Creating a basic SCM secret

Create a secret with your SCM access token by running the `kubectl create` command with a YAML file:

[source,bash]
----
kubectl create -f scm-secret.yaml
----

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: pipelines-as-code-secret
  namespace: <YOUR NAMESPACE>
  labels:
    appstudio.redhat.com/credentials: scm
    appstudio.redhat.com/scm.host: <source-control-management-host> # for example, gitlab.com or github.com
type: kubernetes.io/basic-auth
stringData:
  password: <ACCESS TOKEN>
----

[NOTE]
====
Using the PAT (Personal Access Token) authentication requires only the `password` key. The `username` should not be set. If you set both the `username` and `password` keys, the authentication type will be considered as `basic`, and a basic authentication client will be created using those credentials. This client might not work or can be considered as a deprecated login method by some Source Code Management (SCM) providers.
====

This secret will be used by the build service to perform builds with Pipeline-as-Code.

== Advanced configurations

You can scope secrets to specific repositories or organizations using annotations.

=== Organization-wide secret

To create a secret for all repositories in an organization, add the `appstudio.redhat.com/scm.repository` annotation with a wildcard:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: pipelines-as-code-secret
  namespace: <YOUR NAMESPACE>
  labels:
    appstudio.redhat.com/credentials: scm
    appstudio.redhat.com/scm.host: <source-control-management-host>
  annotations:
    appstudio.redhat.com/scm.repository: my-org/*
type: kubernetes.io/basic-auth
stringData:
  password: <ACCESS TOKEN>
----

=== Repository-specific secret

To create a secret for a specific repository:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: pipelines-as-code-secret
  namespace: <YOUR NAMESPACE>
  labels:
    appstudio.redhat.com/credentials: scm
    appstudio.redhat.com/scm.host: <source-control-management-host>
  annotations:
    appstudio.redhat.com/scm.repository: <repository-path> # for example, my-org/my-repo
type: kubernetes.io/basic-auth
stringData:
  password: <ACCESS TOKEN>
----

[NOTE]
====
* You can have multiple repositories listed under the `appstudio.redhat.com/scm.repository` annotation. Separate repository names with commas when listing them. The secret will be used for all repositories that match the specified paths.

* You can also have multiple secrets with different labels and/or annotations.
====

== Secret lookup mechanism

[IMPORTANT]
====
* The secrets lookup mechanism searches for the most specific secret first. The secret with a repository annotation will be used first if it matches the component repository path. If none is found, then a lookup will try to find a secret with a wildcard, or just the host matching one.

* If you upload a GitHub access token to a tenant namespace, {ProductName} won't use the global GitHub application when accessing GitHub repositories.
====

