= Onboarding a component from GitLab
:description: Onboarding a component from a GitLab repository using access tokens and secrets.

Create components from GitLab repositories using the {ProductName} UI or `kubectl`.

== Prerequisites

* xref:installing:enabling-builds.adoc[Enabled] build pipelines for your instance of {ProductName}.
* link:https://kubernetes.io/docs/tasks/tools/[kubectl] CLI tool
* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started with the CLI] page.
* An existing application in your namespace.

[[creating-a-gitlab-access-token-and-secret]]
== Creating a GitLab access token and secret

Before onboarding a component from GitLab, you must create a source control secret to enable {ProductName} to access your GitLab repository.

.Procedure

. In GitLab click on Settings -> Access Tokens on the left menu of your repository.
+
NOTE: If you do not see this option, ask a user with repository maintainer permissions to create the token.

. Click on `Add new token`.

. If your GitLab instance supports setting token roles, set the role to `Maintainer`.

. Select the following scopes: `api`, `read_repository`, and `write_repository`.

. Click **Create project access token** and copy the generated token.

. Create a secret in your {ProductName} tenant namespace. See xref:building:secrets/creating-scm-secrets.adoc[Creating source control management secrets] for detailed instructions on creating the secret with the token.

[IMPORTANT]
====
* This Project Access Token is scoped to a project, so you cannot use it to access resources from other projects. For more information regarding Project Access Tokens, see the GitLab https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html[documentation].

* If your GitLab project uses restrictive link:https://docs.gitlab.com/ee/user/project/repository/push_rules.html[push rules] to verify users, {ProductName} may fail to push commits to your repository.
====

[[creating-a-component-with-the-ui]]
== Creating a component with the UI

.Prerequisites:

* xref:installing:enabling-builds.adoc[Enabled] build pipelines for your instance of {ProductName}.
* xref:installing:enabling-builds.adoc#enable-image-controller[Enabled] image controller for your instance of {ProductName}.
* An existing application in your namespace.

.Procedure

. In the {ProductName} UI, go to the *Applications* page.
. Click on the name of the application that you want to add a component to.
. Click on *Actions* and *Add component*.
. If a source control secret does not already exist for the repository or the host, click *Add secret* in the *Build time secret* section at the bottom of the page and complete the following fields:
  .. Set *Secret type* to `Source secret`.
  .. Enter a unique name for the secret (for example, `pac-gitlab`).
  .. Set *Authentication type* to `Basic authentication`.
  .. Enter the hostname of your GitLab instance in the *Host* field (for example, `gitlab.com`).
  .. (Optional) Enter the repository path in the *Repository* field to scope the secret to a specific repository (for example, `org/project`). Leave empty to apply the secret to all repositories on the host.
  .. Leave the *Username* field empty.
  .. Enter your access token in the *Password* field. See <<creating-a-gitlab-access-token-and-secret>> for instructions on how to acquire an access token.
  .. Click *Create*.
. Enter the URL for the git repository.
. (Optional) After clicking out of the repository URL, expand the *Show advanced Git options*.
  .. Enter the branch name to the *Git reference* dialog.
  .. Enter the path to the context directory if the build context is contained somewhere other than the repository root.
  .. Select `gitlab` from the *Git provider annotation* drop-down menu.
  .. Enter the base URL of your GitLab instance in the *Git url annotation* field (for example, `https://gitlab.com`).
. Enter the path to the Dockerfile within the git repository. This will be the path within the context directory.
. (Optional) Change the component name if desired.
. (Optional) Click on the *Pipeline* drop down box and select the desired pipeline to configure your component with.
. (Optional) Click on *Add secret* to add any additional secrets needed for the component build. See xref:building:secrets/index.adoc[creating secrets] for more information.
. Click *Add component*.

+
NOTE: When a component is immediately removed after creation, it might result in an orphaned ImageRepository whose ownership was not yet assigned to the component. When trying to create a component again with the same name, the UI will report an error that the ImageRepository already exists. To resolve this, remove the ImageRepository manually from OCP.

== Creating a component with the CLI

. Create a `Component.yaml` file locally.

+
.Example `Component.yaml` object
include::partial$custom-resources/{context}-component-gitlab.adoc[]

+
NOTE: You can also set the 'build.appstudio.openshift.io/request' annotation to 'configure-pac-no-mr'.
If you use this value, a merge request is not created during onboarding,
and you must create the pipeline run YAML files for the component manually.

. Create an `ImageRepository.yaml` file locally.
+
.Example `ImageRepository.yaml` object
include::partial$custom-resources/{context}-imagerepository.adoc[]

. Apply the resource to your namespace by running the following command:

+
[source,shell]
----
$ kubectl apply -f Component.yaml ImageRepository.yaml
----

+
NOTE: You can create additional components by adding their custom resource configurations to the `Component.yaml` file. Separate multiple resources with `---`:
+
[source,yaml]
----
# Component A
---
# Component B
----

. Configure the build pipeline for your component:
.. If the annotation `build.appstudio.openshift.io/request: configure-pac` is set on the component, {ProductName} automatically creates a merge request in your repository with the Tekton pipeline definitions. Review and merge this merge request to complete the setup.
.. If the annotation is not set or is set to `configure-pac-no-mr`, manually create or update the Tekton pipeline files in your repository.

+
NOTE: The PipelineRun will run only for submitters who have permission to run PipelineRuns or who receive an `/ok-to-test` comment from an authorized user. +
For further details on PipelineRun permissions, see the https://pipelinesascode.com/docs/guide/running/[PipelinesAsCode documentation].

. After the pull request is created, a build pipeline starts. Track its progress in the {ProductName} UI or see the final status in GitLab after the pipeline completes. If the pipeline is successful, merge the merge request.

