= Onboarding a component from GitHub
:description: Onboarding a component from a GitHub repository using the GitHub App.

Create components from GitHub repositories using the {ProductName} UI or `kubectl`.

NOTE: Before onboarding a component from GitHub, install the {ProductName} GitHub App on your organization or repository. The GitHub App name is provided by your {ProductName} administrators.

[[creating-a-component-with-the-ui]]
== Creating a component with the UI

.Prerequisites:

* xref:installing:enabling-builds.adoc[Enabled] build pipelines for your instance of {ProductName}.
* xref:installing:enabling-builds.adoc#enable-image-controller[Enabled] image controller for your instance of {ProductName}.
* An existing application in your namespace.
* The {ProductName} GitHub App installed on your organization or repository.

.Procedure

. In the {ProductName} UI, go to the *Applications* page.
. Click on the name of the application that you want to add a component to.
. Click on *Actions* and *Add component*.
. Enter the URL for the git repository.
. (Optional) After clicking out of the repository URL, expand the *Show advanced Git options*.
  .. Enter the branch name to the *Git reference* dialog.
  .. Enter the path to the context directory if the build context is contained somewhere other than the repository root.
. Enter the path to the Dockerfile within the git repository. This will be the path within the context directory.
. (Optional) Change the component name if desired.
. (Optional) Click on the *Pipeline* drop down box and select the desired pipeline to configure your component with.
. (Optional) Click on *Add secret* to add any additional secrets needed for the component build. See xref:building:secrets/index.adoc[creating secrets] for more information.
. Click *Add component*.

+
NOTE: When a component is immediately removed after creation, it might result in an orphaned ImageRepository whose ownership was not yet assigned to the component. When trying to create a component again with the same name, the UI will report an error that the ImageRepository already exists. To resolve this, remove the ImageRepository manually from OCP.

== Creating a component with the CLI

.Prerequisites:

* xref:installing:enabling-builds.adoc[Enabled] build pipelines for your instance of {ProductName}.
* link:https://kubernetes.io/docs/tasks/tools/[kubectl] CLI tool
* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started with the CLI] page.
* An existing application in your namespace.
* The {ProductName} GitHub App installed on your organization or repository.

.Procedure

. Create a `Component.yaml` file locally.

+
.Example `Component.yaml` object
include::partial$custom-resources/{context}-component-github.adoc[]

+
NOTE: Request annotation 'build.appstudio.openshift.io/request' can be set also to 'configure-pac-no-mr' and
then during onboarding the onboarding PR won't be created and users will have to create pipeline run yaml
files for the component manually.

. Create an `ImageRepository.yaml` file locally.
+
.Example `ImageRepository.yaml` object
include::partial$custom-resources/{context}-imagerepository.adoc[]

. Apply the resource to your namespace by running the following command:

+
[source,shell]
----
$ kubectl apply -f Component.yaml ImageRepository.yaml
----

+
NOTE: You can create additional components by adding their custom resource configurations to the `Component.yaml` file. Separate multiple resources with `---`:
+
[source,yaml]
----
# Component A
---
# Component B
----

. Configure the build pipeline for your component:
.. If the annotation `build.appstudio.openshift.io/request: configure-pac` is set on the component, {ProductName} automatically creates a pull request in your repository with the Tekton pipeline definitions. Review and merge this pull request to complete the setup.
.. If the annotation is not set or is set to `configure-pac-no-mr`, manually create or update the Tekton pipeline files in your repository.

+
NOTE: The PipelineRun will run only for submitters who have permission to run PipelineRuns or who receive an `/ok-to-test` comment from an authorized user. +
For further details on PipelineRun permissions, please refer to the https://pipelinesascode.com/docs/guide/running/[PipelinesAsCode documentation].

. Once the pull request is made, a build pipeline should start. Track its progress in the {ProductName} UI or see the final status in GitHub after the pipeline completes. If the pipeline is successful, merge the pull request.
