= Customizing the build pipeline

To meet your specific needs, you can customize the way that {ProductName} builds components. For instance:

* Change the parameters of the build pipeline of a component.
* Configure the timeouts for the pipeline.
* Extend the pipeline with your own tasks (or delete existing tasks).

For example, you might decide to limit how long {ProductName} saves the images that it builds for pull requests. You can set a limit by changing the value of the `image-expires-after` parameter. Or you can ensure that images are compliant with regulations for your industry, by adding a compliance check as a task to the build pipeline.


== Changing parameters

.Procedure

. In the PipelineRun YAML files in the `.tekton` directory, customize the parameters in the `.spec.params` section:
.. You can change the default `value` of existing parameters. For example, for PRs, you could change the value of `image-expires-after` from the default `5d` to `1w`, so images built for PRs expire after a week rather than 5 days.
+
[source,diff]
----
 spec:
   params:
   - name: image-expires-after
-    value: 5d
+    value: 1w
   - name: dockerfile
     value: Dockerfile
----

.. You can also add parameters. New parameters must include a `name` and `value`.
+
[source,diff]
----
 spec:
   params:
+  - name: hermetic
+    value: "true"
   - name: image-expires-after
     value: 1w
   - name: dockerfile
     value: Dockerfile
----
+
Refer to the `params` section in your Pipeline to see the available parameters.
When looking at a PipelineRun file, you can typically find the Pipeline definition in:
+
* The PipelineRun file itself, inlined in `.spec.pipelineSpec`
* A separate file in the `.tekton` directory, referenced by name in `.spec.pipelineRef`
* An external location, referenced by a resolver in `.spec.pipelineRef`

. Commit your changes to the repository of the component.


== Configuring timeouts

By default, your pipeline has a timeout of 1 hour (as does each task in the pipeline individually).
Your builds may take longer than that, in which case you will need to increase the timeouts accordingly.

.Procedure

For example, let's configure the timeouts for a pipeline where the build itself may take up to 3 hours
and antivirus scanning may take up to 2 hours. We'll set corresponding timeouts for both the tasks
and a 6 hour total timeout for the pipeline.

. In the PipelineRun files in the `.tekton` directory, set the `.spec.timeouts`. This is the overall timeout for the pipeline.
+
[source,yaml]
----
kind: PipelineRun
spec:
  timeouts:
    # See https://tekton.dev/docs/pipelines/pipelineruns/#configuring-a-failure-timeout
    pipeline: 6h
----
. In the Pipeline definitions in the `.tekton` directory, set the `timeout` for the relevant tasks:
+
[source,yaml]
----
kind: Pipeline
spec:
  tasks:
    # ...
    - name: build-container
      timeout: 3h
      runAfter:
        - clone-repository
      taskRef: ...
    - name: clamav-scan
      timeout: 2h
      runAfter:
        - build-container
      taskRef: ...
----
+
NOTE: This example shows a separate Pipeline file, but your pipeline may also be defined directly in
    your PipelineRun file(s) (in `.spec.pipelineSpec`), in which case you configure all the timeouts in
    the PipelineRun.


== Extending the build pipeline with your own tasks

.Prerequisites

. (optional) Ensure your build pipeline is using
  xref:./using-trusted-artifacts.adoc[Trusted Artifacts]. This can prevent subsequent failures
  reported by link:https://conforma.dev/docs/policy/packages/release_trusted_task.html#trusted_task__trusted[Conforma's Trusted Tasks]
  check. See xref:./customizing-the-build.adoc#preventing-issues-with-conforma[Preventing Issues with Conforma]
  for more information.

.Procedure

. In each Pipeline definition in the `.tekton` directory, add a new task to the `tasks` section.

+
Example task:
+
[source,yaml]
--
  name: example-task
  params:
  - name: example-param
    value: "Example"
  runAfter:
  - build-container  # You can be more specific by choosing another task
  taskRef:
    params:
    - name: name
      value: example-task  # metadata.name field of the Task
    - name: bundle
      value: quay.io/tekton-bundle-catalog/example-task-bundle:1.0
      # For more details on tekton bundles, refer to https://tekton.dev/docs/pipelines/pipelines/#tekton-bundles
    - name: kind
      value: task
    resolver: bundles
  when:
  - input: $(params.skip-checks)  # This references the pipeline parameters
    operator: in
    values:
    - "false"
--

+
See xref:patterns:slack-notifications.adoc[] for an example of a custom task added to the pipeline that sends a slack notification when the `Pipelinerun` fails.
+

== Preventing issues with Conforma

Custom Tasks may need access to data from other Tasks. However, in order to not break the chain of trust in a build Pipeline, there are restrictions in modifying such data. For example, a custom Task should not be allowed to modify the component's source code. If you are using Conforma to verify your builds, introducing a custom Task may violate the link:https://conforma.dev/docs/policy/packages/release_trusted_task.html#trusted_task__trusted[Trusted Tasks] rule. See xref:./using-trusted-artifacts.adoc[Trusted Artifacts] for how to safely allow share data between Tasks.

== Increasing memory or cpu limits for buildah or any other task

Refer to xref:./overriding-compute-resources.adoc[overriding compute resources].

== Bring your own Quay repository to the build pipeline

By default, all pipelines push the images to a local repository that is set up as a part of installation. Ths registry address is registry-service.kind-registry:5001. It is not mandatory to use this local repo, so if you want to use your own Quay repo to control user permissions, you can do this by following link:https://github.com/konflux-ci/konflux-ci/blob/main/docs/quay.md#configuring-a-push-secret-for-the-build-pipeline[the instructions] for configuring a push secret for the build piepline.

== Verification

When you commit changes to these `.yaml` files in your repository, {ProductName} automatically triggers a new build. Wait for {ProductName} to complete the new build, then verify your changes have been made by following these steps:

. Navigate to *Activity > Pipeline runs*.
. Select the most recent build pipeline run.
. In the *Details* tab, confirm that there are new tasks that you added in the pipeline visualization.
. In the *Logs* tab, confirm the following:
.. Any new tasks are in the navigation bar.
.. If you changed a parameter's value, and that value gets printed, the new value is in the log.

== Troubleshooting

If you experience any issues with your customized pipeline, try the following solutions:

* If you believe that your desired parameter values are not being passed into the pipeline, make sure that your assignment of that value doesn't get overwritten later in the `.yaml` file.

* If your new task is not appearing in the pipeline run, ensure the following:
** You added it to the correct place in the `.yaml` files, so that it has the path `.spec.tasks` or `.pipelineSpec.tasks`.
** You specified a valid `runAfter` field, and that the task in that field completed successfully.

* For problems with both parameters and tasks, make sure you committed your changes to the `.tekton` directory in the repository that {ProductName} references for the component.

== Additional resources [[additional-resources]]

* Documentation on xref:./reconfiguring-build-pipeline.adoc[resetting your build pipeline].
* Tekton docs for link:https://tekton.dev/docs/pipelines/tasks/[Tasks], link:https://tekton.dev/docs/pipelines/pipelines/[Pipelines]
  and link:https://tekton.dev/docs/pipelines/pipelineruns/[PipelineRuns]
** The fundamentals of your build pipeline
* Pipelines as Code docs for link:https://pipelinesascode.com/docs/guide/authoringprs/[PipelineRuns]
** PaC-specific concepts, such as dynamic variables and event matching
