= Prefetching package manager dependencies for hermetic builds

In {ProductName}, you can run a hermetic build by restricting network access to the build; but without network access, a build will not be able to fetch component dependencies from remote repositories, and might fail. To avoid that, {ProductName} can prefetch dependencies for your hermetic builds using link:https://hermetoproject.github.io/hermeto[Hermeto].

For every build, Hermeto generates a software bill of materials (SBOM) where all dependencies are properly declared and pinned to specific versions. Also, Hermeto ensures that arbitrary code is never executed during the prefetch, meaning, for example, that the build doesn't pull any undeclared dependencies. This results in very accurate SBOMs and improved build reproducibility. For more information about SBOMs, see xref:metadata:sboms.adoc[Inspecting SBOMs].

[#available-package-managers]
.Available package managers

[cols="1,1"]
|===
|**Package manager**
|**Programming language**

|xref:gomod[gomod]
|`Go`

|xref:pip[pip]
|`Python`

|xref:npm[npm]
|`JavaScript`

|xref:yarn[yarn]
|`JavaScript`

|xref:bundler[bundler]
|`Ruby`

|xref:cargo[cargo]
|`Rust`

|xref:rpm[rpm]
|`N/A`

|xref:generic[generic]
|`N/A`
|===

== Procedure
To prefetch dependencies for a component build, complete the following steps:

. Go to the `.tekton` directory and find the `.yaml` files related to the `*pull request*` and `*push*` processes.

. Configure the hermetic pipeline by adding the following parameters in both `.yaml` files:

+
[source,yaml]
----
pipelineSpec:
  params:
    ...
    - name: hermetic
      type: string
      description: Execute the build with network isolation
      default: "true"
----

+
[source,yaml]
----
spec:
  params:
    ...
    - name: prefetch-input
      value: '{"type": "<package_manager>", "path": ".", "some_other_key": "some_other_value"}' <1>
----
<1> The prefetch-input parameter specifies the path to the directory of the project. In this example, the `.` indicates the repository root. If you have multiple directories, you can provide the path to those directories in the JSON array format: `[{"type": "<package_manager>", "path": "."}, {"type": "<package_manager>", "path": "subpath/to/the/other/directory"}]`. Additionally, you can add other keys and values to the JSON object supported by specific package managers.

. Create a pull request by committing your changes to the repository of the component.

. Review and merge the pull request.

[IMPORTANT]
====
Refer to the link:https://hermetoproject.github.io/hermeto/usage[hermetic build walkthrough] for more detail on configuration and usage.

include::partial${context}-prefetch-hermeto-note.adoc[]
====

== Verification
* From the {ProductName} *Applications* view, go to *Activity > Pipeline runs*.
** Go to the pipeline run with *Build* in the *Type* column and confirm that the `prefetch-dependencies` stage displays a green checkmark. This indicates that the build process successfully fetched all dependencies.
* From the {ProductName} *Applications* view, go to *Activity > Latest commits*.

== Troubleshooting
If your build fails, be sure to look at your logs:
In {ProductName}, from the *Applications* view, select the application build you want to troubleshoot, then from the resulting *Overview* page, select the *Activity* tab. From there, under *Activity By*, select *Pipeline runs*. From the *Name* column, select the build whose logs you want to check, then from the resulting *Pipeline run details* view, do one of the following:

* Select the *Logs* tab.
* Alternatively, you can click *build-container*. When the right panel opens, select the *Logs* tab to see a partial view of the log for that build.

== [[gomod]]Enabling prefetch builds for `gomod`

.Prerequisites
* You have a `go.mod` file in your repository that lists all the dependencies.

=== [[go-private]]Prefetching Go modules from private repos

To enable downloading modules from private repos, Go supports authentication via `.netrc`.
You can create a netrc Secret for your pipeline as described xref:netrc[below].
For more Go-specific `.netrc` details, see the link:https://go.dev/doc/faq#git_https[Go docs].

=== [[go-walkthrough]]`gomod` walkthrough

[IMPORTANT]
====
Refer to the link:https://hermetoproject.github.io/hermeto/gomod#example[gomod hermetic build walkthrough] for more detail on configuration and usage.

include::partial${context}-prefetch-hermeto-note.adoc[]
====

== [[pip]]Enabling prefetch builds for `pip`
Hermeto supports pip by parsing of `pip` requirements files, including but not limited to, `requirements.txt` files placed in the root of your repository. By generically parsing `pip` requirements files, Hermeto downloads the specified dependencies.

IMPORTANT: These requirements files function as lockfiles, encompassing all transitive dependencies. You must actively pin each transitive dependency listed in the requirements file to a specific version. Check the link:https://hermetoproject.github.io/hermeto/pip/#requirementstxt[Hermeto documentation] for more information on how to generate the requirements file.

=== Building from source
By default, Hermeto will only fetch the source distribution from each dependency present in the requirements file. This is to force `pip` to build every dependency from source instead of relying on pre-built wheels, bringing a greater transparency to the content that will be made available to the build.

In many cases, it is necessary to include additional build dependencies that are not automatically added by `pip-compile` on the requirements file. To overcome this limitation, we recommend the use of the link:https://pybuild-deps.readthedocs.io/en/latest/index.html[pybuild-deps] tool. This tool will generate a `requirements-build.txt` that contains all the build dependencies that are needed to build the project from source.

== Procedure
To prefetch dependencies for a component build, complete the following steps:

. Go to the `.tekton` directory and find the `.yaml` files related to the `*pull request*` and `*push*` processes.
. Configure the hermetic pipeline by adding the following parameters in both `.yaml` files:

[source,yaml]
----
spec:
    params:
        -   ...
        -   name: prefetch-input
            value: '{"type": "pip", "path": "."}'
----

[NOTE]
====
* By default, Hermeto processes `requirements.txt` and `requirements-build.txt` at a specified path.
====

.. Optional: In case the requirements files do not use the standard names, or in case more than a single requirements or requirements-build file is needed, you can use the following additional parameters:

+
[source,yaml]
----
spec:
    params:
        -   ...
        -   name: prefetch-input
            value: '{"type": "pip", "path": ".", "requirements_files": ["requirements.txt", "requirements-extras.txt", "tests/requirements.txt", "requirements_build_files": ["other-build-requirements.txt"]}'
----

NOTE: To troubleshoot any issues you might experience when you enable prefetch builds for `pip` with source dependencies, see the link:https://hermetoproject.github.io/hermeto/pip/#troubleshooting[Hermeto documentation]

=== Building by enabling the prefetching of wheels

In case you don't want to build every dependency from source, Hermeto can be configured to also fetch wheels alongside the source distributions:

[source,yaml]
----
spec:
    params:
        -   ...
        -   name: prefetch-input
            value: '{"type": "pip", "path": ".", "allow_binary": true}'
----

Note that you don't need to generate a `requirements-build.txt` file as described in the section above in case the prefetching of wheels is enabled.

=== [[custom-index-servers]]Prefetching `pip` dependencies from custom index servers

Hermeto supports pip's link:https://pip.pypa.io/en/stable/cli/pip_install/#install-index-url[--index-url] option.
You can add this option to your `requirements.txt` file(s), instructing Hermeto to download packages from the specified
index server. For example:

[source,text]
----
--index-url=https://example.pypi.org/simple/
requests==2.32.2 \
    --hash=sha256:dd951ff5ecf3e3b3aa26b40703ba77495dab41da839ae72ef3c8e5d8e2433289 \
    --hash=sha256:fc06670dd0ed212426dfeb94fc1b983d917c4f9847c863f313c9dfaaffb7c23c

# ...other packages
----

WARNING: Do not include credentials in the index URL. If needed, provide authentication through a `.netrc` file (as described xref:netrc[below]).
For more pip-specific details on netrc files, review the link:https://pip.pypa.io/en/stable/topics/authentication/#netrc-support[pip documentation for netrc support].

=== [[pip-walkthrough]]`pip` walkthrough

[IMPORTANT]
====
Refer to the link:https://hermetoproject.github.io/hermeto/pip#example[pip hermetic build walkthrough] for more detail on configuration and usage.

include::partial${context}-prefetch-hermeto-note.adoc[]
====

== [[npm]]Enabling prefetch builds for `npm`
Hermeto supports `npm` by fetching any dependencies you declare in your `package.json` and `package-lock.json` project files. The npm CLI manages the `package-lock.json` file automatically, and Hermeto fetches any dependencies and enables your build to install them without network access.

.Prerequisites
* You have an up-to-date link:https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json[`package-lock.json`] file, newer than version 1, in your source repository. To make sure that you have the latest `package-lock.json` file, or to create a lockfile, run the link:https://docs.npmjs.com/cli/v9/commands/npm-install?v=true[`npm-install`] command. You can also look at the `lockfileVersion` attribute in your `package-lock.json` file to make sure its value is a number greater than `*1*`.

=== [[npm-walkthrough]]`npm` walkthrough

[IMPORTANT]
====
Refer to the link:https://hermetoproject.github.io/hermeto/npm#example[npm hermetic build walkthrough] for more detail on configuration and usage.

include::partial${context}-prefetch-hermeto-note.adoc[]
====

== [[yarn]]Enabling prefetch builds for `yarn`

Supported versions: 1.x, 3.x, and 4.x. Hermeto automatically detects the version of `yarn` and fetches any dependencies you declare in your `package.json` and `yarn.lock` project files.

.Prerequisites

* You have an up-to-date `yarn.lock` file in your source repository. To ensure you have the latest `yarn.lock` file or to create it, run the `yarn install` command. If `yarn.lock` is not up-to-date, Hermeto will not fetch the dependencies.

=== [[yarn-walkthrough]]`yarn` walkthrough

[IMPORTANT]
====
Refer to the link:https://hermetoproject.github.io/hermeto/yarn#example[yarn hermetic build walkthrough] for more detail on configuration and usage.

include::partial${context}-prefetch-hermeto-note.adoc[]
====

== [[bundler]]Enabling prefetch builds for `bundler`

.Prerequisites

You have a `Gemfile` and a `Gemfile.lock` file in your repository that lists all the dependencies. The `Gemfile.lock` is generated from the `Gemfile` and contains all transitive dependencies pinned to specific versions.

=== [[bundler-walkthrough]]`bundler` walkthrough

[IMPORTANT]
====
Refer to the link:https://hermetoproject.github.io/hermeto/bundler#hermetic-build[bundler hermetic build walkthrough] for more detail on configuration and usage.

include::partial${context}-prefetch-hermeto-note.adoc[]
====

== [[cargo]]Enabling prefetch builds for `cargo`

.Prerequisites

You have a `Cargo.lock` file in your repository that lists all the dependencies. The `Cargo.lock` file is generated by running the `cargo generate-lockfile` command and contains all transitive dependencies pinned to specific versions.

=== [[cargo-walkthrough]]`cargo` walkthrough

[IMPORTANT]
====
Refer to the link:https://hermetoproject.github.io/hermeto/cargo#hermetic-build[cargo hermetic build walkthrough] for more detail on configuration and usage.

include::partial${context}-prefetch-hermeto-note.adoc[]
====

== [[rpm]]Enabling prefetch builds for `rpm`

Hermeto has a package manager capable of fetching `rpm` dependencies. This requires the use of a pair of `rpms.in.yaml` and `rpms.lock.yaml` files to be committed to your repository. You write a `rpms.in.yaml` file and the link:https://github.com/konflux-ci/rpm-lockfile-prototype?tab=readme-ov-file#what-is-this[rpm-lockfile-prototype] CLI tool resolves that to produce a `rpms.lock.yaml` file. Hermeto fetches those specific rpms and enables your build to install them without network access.

.Prerequisites
* You have an up-to-date installation of link:https://github.com/konflux-ci/rpm-lockfile-prototype?tab=readme-ov-file#installation[rpm-lockfile-prototype].

To prefetch dependencies for a component build, complete the following steps:

. Have a Containerfile, for example:
+
include::partial${context}-example-prefetch-rpm-containerfile.adoc[]

. Create a `rpms.in.yaml` file in your git repository, with the following contents:

+
include::partial${context}-example-prefetch-rpm-rpms_in_yaml.adoc[]
<1> The `*packages*` list is the list of packages you want to install in your Container. You don't have to declare transitive dependencies here. The rpm-lockfile-prototype tool will resolve them for you.
<2> This should be a reference to a repo file, like those found in `/etc/yum.repos.d/`. This tells the tooling where to find your rpm and its dependencies.
<3> The `arches` array allows you to specify which architectures the dependencies should be downloaded for. If you're building a multi-arch container this array is mandatory, otherwise the build task will fail.
+
NOTE: The description of all options available for `rpms.in.yaml` can be found
https://github.com/konflux-ci/rpm-lockfile-prototype?tab=readme-ov-file#whats-the-input_file[here].

. Copy any necessary yum/dnf repo files into your git repository. For example:

+
include::partial${context}-example-prefetch-rpm-copy-repo.adoc[]

. (Optional) If you're installing the RPMs into a custom install root, e.g. `dnf install --installroot`, be sure to import the required GPG keys into the custom install root first:

+
include::partial${context}-example-prefetch-rpm-trust-keys.adoc[]

+
NOTE: For every repository defined in your set of repo files, make sure to add the corresponding sources repo (or make sure to enable them, if they're already present). Otherwise, the lockfile generator will not include any SRPMs in your lockfile, Hermeto won't download any SRPMs, and the source container for your build will be incomplete.

. Run the following command to resolve your `rpms.in.yaml` file and produce a `rpms.lock.yaml` file.

+
include::partial${context}-example-prefetch-rpm-execute.adoc[]
<1> The produced `rpms.lock.yaml` file will include only your requested dependency plus its transitive dependencies, minus any rpms that are already installed in the provided base image.
+
Example of generated lockfile:
+
include::partial${context}-example-prefetch-rpm-lockfile.adoc[]
+
NOTE: The list of `arches.packages` is omitted for brevity.

. Add/Update the prefetch-input param in the PipelineRun YAML so that the prefetch-task for RPMs is enabled. Update the path if the RPM files are not in the default directory.
+
[source,yaml]
----
spec:
  params:
    ...
    - name: prefetch-input
      value: '{"type": "rpm", "path": "."}' <1>
----

. You can specify additional DNF repository configuration options (see `dnf.conf` man page) that will be set for a particular repository in the generated `hermeto.repo` files
+
include::partial${context}-example-prefetch-rpm-dnf-repo-options.adoc[]

NOTE: Konflux also supports prefetching RPM content which requires a Red Hat subscription. For more information see xref:./activation-keys-subscription.adoc#hermetic-network-isolated-builds[Using Red Hat activation keys to access subscription content].

=== [[rpm-walkthrough]]`rpm` walkthrough

[IMPORTANT]
====
Refer to the link:https://hermetoproject.github.io/hermeto/rpm#example[rpm hermetic build walkthrough] for more detail on configuration and usage.

include::partial${context}-prefetch-hermeto-note.adoc[]
====

== [[generic]]Enabling prefetch builds for `generic fetcher`
If you need to prefetch arbitrary files for your build, Hermeto supports `generic fetcher` for that purpose. It uses a custom lockfile named `artifacts.lock.yaml` to achieve this. This file needs to be either commited in the source repository, or explicitly specified as an absolute path. The latter is useful in case you for some reason need the lockfile to be dynamic and committing it to the repository would be problematic. For more information on supported types of artifacts, see the link:https://hermetoproject.github.io/hermeto/generic[Hermeto documentation].

To prefetch dependencies for a component build, complete the following steps:

. Create an `artifacts.lock.yaml` file in your git repository, with a list of files to prefetch, their checksums, and optionally their filenames. See the link:https://hermetoproject.github.io/hermeto/generic[Hermeto documentation] for complete overview of the lockfile format.

+
[source,yaml]
----
---
metadata: <1>
  version: "1.0"
artifacts:
  - download_url: "https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.0/dependency-check-11.1.0-release.zip"
    checksum: "sha256:c5b5b9e592682b700e17c28f489fe50644ef54370edeb2c53d18b70824de1e22" <2>
    filename: "dependency-check.zip" <3>
----
<1> `metadata` section is required and needs to specify lockfile version
<2> `checksum` is expected to be specified as `algorith:hash`
<3> If no `filename` is specified, it will be derived from the URL.

=== Using your prefetched generic assets
You can find your generic prefetched assets in `/cachi2/output/deps/generic/<filename>` and access them in your `Containerfile`:

[source, Dockerfile]
----
RUN cp /cachi2/output/deps/generic/<filename> <location>
----

=== [[generic-walkthrough]]`generic fetcher` walkthrough

[IMPORTANT]
====
Refer to the link:https://hermetoproject.github.io/hermeto/generic/#example[generic fetcher hermetic build walkthrough] for more detail on configuration and usage.

include::partial${context}-prefetch-hermeto-note.adoc[]
====

== [[netrc]]Creating the netrc secret

The `prefetch-dependencies` task supports link:https://everything.curl.dev/usingcurl/netrc.html[.netrc] files for authentication.
For example, it is useful for:

* xref:custom-index-servers[pip packages from private index servers]
* xref:go-private[Go modules from private repos]

To create a netrc Secret for use in your pipelines:

. Create the `.netrc` file locally. See the link:https://everything.curl.dev/usingcurl/netrc.html[.netrc] docs for more details on the file format.
. Create a key/value secret (see xref:building:creating-secrets.adoc[creating secrets for your builds]).
  Set `.netrc` as the key. Upload the content of your `.netrc` file as the value.
. In your `.tekton/` PipelineRun files, add the newly created secret to the `.spec.workspaces` section:

+
[source,yaml]
----
spec:
  # ...
  workspaces:
    # ...
    - name: netrc
      secret:
        secretName: my-netrc  # the name you assigned to the secret in step 2
----

. In the `.spec.pipelineSpec.tasks` section, find the entry with `name: prefetch-dependencies`.
  Add the `netrc` workspace to the list of workspaces (if not present):

+
[source,yaml]
----
    tasks:
      # ...
      - name: prefetch-dependencies
        # ...
        workspaces:
          # ...
          - name: netrc
            workspace: netrc
----
