= Building an Operator Lifecycle Manager (OLM) Operator in {ProductName}

If you are developing an application that aligns with the link:https://operatorframework.io/[Operator Framework], and managing it with link:https://olm.operatorframework.io/docs/[Operator Lifecycle Manager (OLM)], you can build that application in {ProductName}. We refer to such applications as OLM Operators. 

OLM Operators include the following elements:

* Operands, which are components or resources used by the application
* Operator, which manages Operands
* Bundle, which describes how to deploy a version of the application's Operands and Operator as defined by a ClusterServiceVersion (CSV) file
* File-based catalogs, which describe how users can upgrade between different Bundle versions.

Note the difference between an "OLM Operator" and an "Operator." An OLM Operator refers to the whole application, and an Operator is one part of the OLM Operator.

The first procedure in this document explains how to use {ProductName} to build an OLM Operator in the most basic sense--building its Operator and bundle images. The second procedure is optional but recommended. It explains how you can automatically update the image references in the CSV of the bundle. The third procedure describes the process for generating the file-based catalog to inform OLM how to upgrade between OLM Operator versions.


== Building the Operator and the bundle

[NOTE] 
====
This procedure assumes that the source code for your Operator and bundle, including the Dockerfiles, are in the same git repository, per OLM convention.
====

.Procedure

. In the {ProductName} UI,  xref:../how-tos/creating.adoc[create a new application] for your OLM Operator in {ProductName}.
. In your new application, xref:../how-tos/creating.adoc[add a new component] for your Operator. Be sure to specify the correct path to the Operator's Dockerfile within its git repository.
. Add another component for your bundle. Enter the same URL that you used for the Operator, but enter the path to the bundle's Dockerfile.
. (Optional) If you are using a file-based Catalog (FBC) for your OLM Operator, you must build the FBC as another component in its own separate application in {ProductName}.
. (Optional) You may want to configure {ProductName} to xref:../how-tos/configuring/redundant-rebuilds.adoc[prevent redundant rebuilds] for this application. For example, you can configure {ProductName} to rebuild your bundle image only if a commit is made to its Dockerfile or the `/bundle` directory, instead of rebuilding it whenever any commit is made to your OLM Operator's git repository. 

== Automating updates for image references in the CSV

In order to enable your operator to be installed in disconnected environments, it is important to include sha digest image references in the link:https://sdk.operatorframework.io/docs/olm-integration/generation/#csv-fields[CSV's `spec.relatedImages`].

.Procedure

. In the {ProductName} UI, in your OLM Operator's application, go to the *Components* tab and copy the URL for the Operator's container image. The URL should include `sha256:`.
. Using your preferred text editor, in the git repo for your OLM Operator, open the CSV file for your bundle. In that file, update the image reference to the Operator to be the URL you just copied. Commit this change.
. In the {ProductName} UI, follow the instructions in xref:../how-tos/configuring/component-nudges.adoc[this document] to define the relationship between the Operator and the bundle. The Operator nudges the bundle.
. (Optional) For any Operands with image references in your bundle's CSV, you can repeat this same basic process:
.. Add the Operands as components in {ProductName}.
.. Wait for the first build of those components to finish.
.. Copy the URL to the images and paste it as a reference in the bundle's CSV file.

== Maintaining valid image references before a release

When images are xref:/advanced-how-tos/releasing/index.adoc[released] they will be copied to another image repository so any pinned references will be invalid. To surmount this, {ProductName} enables your bundle to be pinned to image references which will be valid after release.

.Procedure

. Configure your xref:/advanced-how-tos/releasing/create-release-plan-admission.adoc[release plan admission] which will copy the images to a new repository.
. In the `spec.data.mapping.components` create a list of component mappings to the target repository

+
*Example partial `ReleasePlanAdmission.yaml` object*

+
[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
spec:
 applications:
  - demo-app <.>
 data:
   mapping:
     components: <.>
       - name: demo-component-1
         repository: target-image-repository-1
       - name: demo-component-2
         repository: target-image-repository-2
 origin: <dev-workspace> <.>

----

+
<.> A list of applications that will contain components to be released.
<.> A list containing the target repository for each component
<.> The development team workspace where the applications and components are defined.

. Using your preferred text editor, in the git repo for your OLM Operator, open the CSV file for your bundle. In that file, update the image references to all images that will be released to the target repository from the RPA (the sha digests should remain unchanged). Commit this change.

+
NOTE: Once this change is merged, the bundle will be invalid until all referenced images are released. In order to test the bundles in an environment, you will need to use a registry mirror like an link:https://docs.openshift.com/container-platform/4.16/rest_api/config_apis/imagedigestmirrorset-config-openshift-io-v1.html[ImageDigestMirrorSet].

.*Verification*

. Commit a change to an Operand or Operator triggering a push event.
. After the build is completed, a pull request should be opened against your bundle's git repository.


== Building the file-based catalog

.Procedure

. In the {ProductName} UI,  xref:../how-tos/creating.adoc[create a new application] for your file-based catalog (FBC) in {ProductName}.
. In your new application, xref:../how-tos/creating.adoc[add a new component] for your FBC. Be sure to select the file-based catalog pipeline and to specify the correct path to the catalog's Containerfile within its git repository.
