= Creating applications and components

== Onboarding components to {ProductName}

{ProductName} supports two methods for creating applications and components.

Before being able to onboard a component to {ProductName}, you will need to ensure that the instance has appropriate access to the git repository. This means either installing your organization’s {ProductName} GitHub App on the source code repository or xref:/building/creating-secrets.adoc#creating-source-control-secrets[create a secret] to enable access to a GitLab repository.

=== With the UI
.Prerequisites:

* xref:/installing/enabling-builds.adoc[Enabled] build pipelines for your instance of {ProductName}.
* xref:/installing/enabling-builds.adoc#enable-image-controller[Enabled] image controller for your instance of {ProductName}.

==== Create initial Application and Component
.*Procedures*

. In the {ProductName} UI, go to the *Applications* page.
. Click the *Create application* button.
. Enter a name for the application
. Click the *Add a component* button.
+
NOTE: For *Gitlab* provider, make sure to xref:/building/creating-secrets.adoc#creating-source-control-secrets[create a source control secret] before creating the component.
  . Enter the URL for the git repository.
  . (Optional) After clicking out of the repository URL, expand the *Show advanced Git options*.
    . Enter the branch name to the *Git reference* dialogue.
    . Enter the path to the context directory if the build context is contained somewhere other than the repository root.
  . Enter the path to the Dockerfile within the git repository. This will be the path within the context directory.
  . (Optional) Change the component name if desired.
  . (Optional) Click on the *Pipeline* drop down box and select the desired pipeline to configure your component with.
  . (Optional) Click on *Add secret* to add a secret which will be needed for the component build. See xref:/building/creating-secrets.adoc[creating secrets] for more information.
. Click *Create application*.

+
NOTE: GitHub and GitLab are supported source control providers. GitLab support requires the configuration of xref:/building/creating-secrets.adoc#creating-source-control-secrets[source control secrets].

==== Create additional Components in an Application

.*Procedures*

. In the {ProductName} UI, go to the *Applications* page.
. Click on the name of the application that you want to add a component to.
. Click on *Actions* and *Add component*.
. Follow the procedure above for specifying the component.
. Click *Add component*.

=== With the CLI

.Prerequisites:

* xref:/installing/enabling-builds.adoc[Enabled] build pipelines for your instance of {ProductName}.
* link:https://kubernetes.io/docs/tasks/tools/[kubectl] CLI tool
* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started in the CLI] page.

.*Procedures*

. Create an `Application.yaml`, `Component.yaml`, and `ImageRepository.yaml` files locally.

+
*Example `Application.yaml` object*
+
include::ROOT:partial$custom-resources/{context}-application.adoc[]

+
*Example `Component.yaml` object*
+
include::ROOT:partial$custom-resources/{context}-component.adoc[]

+
*Example `ImageRepository.yaml` object*
+
include::ROOT:partial$custom-resources/{context}-imagerepository.adoc[]

. In your workspace, save the `Application.yaml`, `Component.yaml`, and `ImageRepository.yaml` files and add the resource to your cluster by running the following command:

+
[source,shell]
----
$ kubectl apply -f Application.yaml -f Component.yaml -f ImageRepository.yaml
----

+
NOTE: You can create additional components and applications with the same file locally by adding additional custom resource configurations. 

. Now, you can trigger your application’s first build pipeline. In the git repository for your application, using your preferred text editor, open a pull request against the `/.tekton/pull-request.yaml` file. 
.. Specifically, replace any existing value for the `git-url` field with the git URL for your application’s repository. (This is the URL you would use to clone the repository locally; it ends with `.git`.)

+
NOTE: The PipelineRun will run only for submitters who have permission to run PipelineRuns or who receive an `/ok-to-test` comment from an authorized user. +
For further details on PipelineRun permissions, please refer to the https://pipelinesascode.com/docs/guide/running/[PipelinesAsCode documentation].

. Once the PR is made, a build pipeline should start. You can track its progress in the {ProductName} UI or you can see the final status in GitHub after the pipeline completes. If the pipeline is successful, you can merge the PR.

== Finding the built images

After a pipeline completes with a built artifact, you may want to test the resulting image to ensure that it works properly. The `IMAGE_URL` Tekton result (discoverable from the UI or CLI) should be set to the pullspec for the image.

NOTE: {ProductName} automatically deletes images built for PR pipelines five days after building them.

=== With the UI

All build PipelineRuns are visible in the {ProductName} UI. The location of these images in the OCI registry is reported on the *Activity* page.

.Procedure

In the console, complete the following steps to find the image pullspec for a completed PipelineRun:

. Navigate to the *Activity* > *Pipeline runs* tab.

. For the component whose SBOM you want to view, select its most recent pipeline run.

. Find the *Results* section at the bottom of the page and look for the `IMAGE_URL` row. It should resemble `quay.io/redhat-user-workloads/workspace-tenant/application/component:tag`. You can use the `IMAGE_DIGEST` provided as an alternate mechanism for referencing the image.

=== With the CLI

After the build PipelineRuns are completed from git push events, the Components are updated with the location of the artifact in the OCI registry.


.Prerequisites

* xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Login] to {ProductName}.

* Install the link:https://stedolan.github.io/jq/download/[jq] CLI tool.

.Procedure

In the CLI, complete the following steps to find the latest pullspec for a component:

. List your components.
+
[source]
----
$ kubectl get components
----
+
.Example output
+
[source]
----
NAME                               AGE   STATUS   REASON   TYPE
devfile-sample-go-basic-8wqt       8m54s True     OK       Updated
devfile-sample-python-basic-ikch   20d   True     OK       Updated
----

. Choose which component's image you want to discover. Then use `kubectl get` and the `jq` CLI tool to get the component image path.

+
[source]
----
$ kubectl get component <component name> -o json | jq '.status.containerImage'
----

. For convenience, you may want to save the image path to a local variable.
+
Example:
+
[source]
--
IMAGE=quay.io/redhat-user-workloads/workspace-tenant/application/component@sha256:<output omitted>
--
