= Triggering Periodic Integration Tests
:description: Running integration tests on a schedule via CronJobs and snapshot labeling.

In {ProductName}, you can run integration tests on a schedule using Kubernetes CronJobs.

== Procedure

To trigger a periodic Integration Test, complete the following steps:

. Create an integration test by following the xref:testing:integration/creating.adoc[Creating a integration test guide].

[NOTE]
====
If the Integration Test is designed to only run periodically rather than during Pull Request checks or post-merge, you need to add the *disabled* xref:testing:integration/choosing-contexts.adoc[context] to the Integration Test.
====

. Create RBAC rules in your tenant to allow CronJob ServiceAccount to access snapshot.

. Create a link:https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/[CronJob] that will trigger periodic Integration Tests via xref:testing:integration/rerunning.adoc[snapshot labels].

=== Procedure with example

This procedure details how to grant the necessary snapshot access to a ServiceAccount, which is required to run periodic Integration Tests. It assumes you have an integration test created and a ServiceAccount available in your tenant namespace.

include::partial$integration/periodic-integration-tests-rbac.adoc[]

[start=3]

. Create a CronJob that will trigger a Periodic Integration Test scenario via snaphot labels.

The following CronJob example configured to run every two days (`*/2` in the schedule). It triggers an integration test scenario in Konflux by:

- Fetching the latest valid snapshot associated with push events in the specified tenant.
- Checking if a valid snapshot exists and is autoreleased successfully; if not, the job exits with an error.
- Labeling the snapshot to initiate the integration test scenario

This process helps ensure that the integration tests are executed periodically using the most recent in main branch.

[source,yaml]
----
kind: CronJob
apiVersion: batch/v1
metadata:
  name: periodic-integration-test
  namespace: default-tenant <.>
spec:
  schedule: '0 0 */2 * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: trigger-e2e-scenario
              image: 'quay.io/konflux-ci/task-runner:v1'
              imagePullPolicy: Always
              command:
                - /bin/bash
                - '-c'
              args:
                - |
                  #!/bin/bash
                  set -euo pipefail

                  export KONFLUX_SCENARIO_NAME="integration-test" <.>
                  export KONFLUX_TENANT_NAME="default-tenant" <.>
                  export KONFLUX_APPLICATION_NAME="application-default" <.>
                  export KONFLUX_COMPONENT_NAME="component-default" <.>

                  echo -e "[INFO] Fetching latest snapshot from ${KONFLUX_TENANT_NAME} related to push events."

                  LATEST_SNAPSHOT=$(kubectl get snapshots -n "${KONFLUX_TENANT_NAME}" -o json | \
                      jq --arg application "$KONFLUX_APPLICATION_NAME" --arg component "$KONFLUX_COMPONENT_NAME" -r '
                          .items
                          | map(select(
                              .metadata.labels."appstudio.openshift.io/application" == $application and
                              .metadata.labels."appstudio.openshift.io/component" == $component and
                              .metadata.labels."pac.test.appstudio.openshift.io/event-type" == "push" and
                              (.status.conditions // [] | map(select(
                                  .type == "AutoReleased" and
                                  .reason == "AutoReleased" and
                                  .status == "True"
                                  ))
                              | length > 0)
                              ))
                          | sort_by(.metadata.creationTimestamp) | last | .metadata.name')

                  if [[ -z "${LATEST_SNAPSHOT}" || "${LATEST_SNAPSHOT}" == "null" ]]; then
                    echo -e "[ERROR] No valid snapshot found. The job will not be triggered."
                    exit 1
                  fi

                  echo -e "[INFO] Triggering test scenario ${KONFLUX_SCENARIO_NAME} from snapshot ${LATEST_SNAPSHOT}."

                  kubectl -n "${KONFLUX_TENANT_NAME}" label snapshot "${LATEST_SNAPSHOT}" test.appstudio.openshift.io/run="${KONFLUX_SCENARIO_NAME}"

                  echo "[INFO] Integration Service E2E tests successfully triggered!"
          restartPolicy: Never <.>
          serviceAccountName: default
          serviceAccount: default
----
<1> The name of the tenant.
<2> The Integration Test name to be triggered by the CronJob.
<3> The tenant from where to annotate the component snapshot to trigger Periodic Integration Test.
<4> The {ProductName} application name associated with the Integration Test that will be triggered by the CronJob.
<5> The {ProductName} component name.
<6> Restart Policy can be "Never" or "OnFailure".

Once the CronJob is triggered and completes, your integration test pipelines should begin executing in the {ProductName} UI.
