= Enabling build pipelines

Before users can create an application in {ProductName}, you must enable build pipelines in your instance of {ProductName}. At the time of publication, this process includes configuring a smee channel, to listen for users' pull requests, and creating a xref:installing:github-app.adoc[GitHub App], so {ProductName} can access those PRs.

.Prerequisites:

* Install link:https://github.com/konflux-ci/konflux-ci/tree/main[{ProductName}]
* Read/write access to your {ProductName} instance’s repository

.Procedure:

. Start a new link:https://smee.io/[smee] channel.
. In the repository for your instance of {ProductName}, edit the file /smee/smee-client.yaml. Replace `<smee-channel>` with the webhook proxy URL from the previous step.
. Create GitHub App according to link:https://pipelinesascode.com/docs/install/github_apps/#manual-setup[these Pipelines as Code instructions]. For the *Webhook URL* field, use the webhook proxy URL for your smee channel.

.Verification

* To verify that you successfully enabled build pipelines, a user should try to xref:building:creating.adoc[create an application].

NOTE: The PipelineRun will run only for submitters who have permission to run PipelineRuns or who receive an `/ok-to-test` comment from an authorized user. +
For further details on PipelineRun permissions, please refer to the https://pipelinesascode.com/docs/guide/running/[PipelinesAsCode documentation].

== Enabling component creation with the UI [[enable-image-controller]]

A controller can be deployed to simplify the lifecycle management of image repositories in quay.io. Documentation for this process can be found in the link:https://github.com/konflux-ci/konflux-ci/blob/main/docs/quay.md#automatically-provision-quay-repositories-for-container-images[installation docs].

Creating components with the UI requires that an additional controller is deployed to manage the automatic creation of quay image repositories.

This controller can be used to create image repositories scoped to individual components. It is also required to be deployed in order to enable creating components from the {ProductName} UI.

== Customizing the available build pipelines [[customize-pipelines]]

The build service uses a **ConfigMap** to determine what Tekton pipelines can be configured when onboarding components. By default, there are link:https://github.com/konflux-ci/konflux-ci/blob/main/konflux-ci/build-service/core/build-pipeline-config.yaml[five pipelines] available. In order to update the pipelines to more recent versions of the pipelines or to add additional pipelines for configuration, update the `build-pipeline-config` resource.

This **ConfigMap** can contain references to any Tekton pipeline bundles. Additional pipelines can be created, pushed to an image repository using link:https://github.com/tektoncd/cli/blob/main/docs/cmd/tkn_bundle.md[`tkn bundle`], and added to the **ConfigMap**.

=== Build pipelines available in quay.io/konflux-ci [[available-pipelines]]

In order to support different use cases within {ProductName}, multiple Tekton pipeline bundles are available in the `quay.io/konflux-ci` organization.

NOTE: The tasks included in the pipeline definitions can be discovered using `yq` or `jq`. For example,
```bash
$ tkn bundle list -o yaml quay.io/konflux-ci/tekton-catalog/pipeline-docker-build:devel pipeline docker-build 2>/dev/null | yq ".spec.tasks.[].name"
init
clone-repository
prefetch-dependencies
build-container
build-image-index
build-source-image
deprecated-base-image-check
clair-scan
ecosystem-cert-preflight-checks
sast-snyk-check
clamav-scan
apply-tags
push-dockerfile
```

==== _docker-build_ [[docker-build]]

This pipeline is ideal for building container images from a Containerfile while reducing network traffic.

_Uses `buildah` to create a container image. It also optionally creates a source images and runs some build-time tests. EC will flag a violation for link:https://conforma.dev/docs/ec-policies/release_policy.html#trusted_task__trusted[trusted_task.trusted] if any tasks are added to the pipeline.
(link:https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-docker-build?tab=tags[quay.io link], link:https://github.com/konflux-ci/build-definitions/blob/main/pipelines/docker-build/README.md[parameter documentation])_

==== _docker-build-oci-ta_ [[docker-build-oci-ta]]

This pipeline is ideal for building container images from a Containerfile while maintaining trust after pipeline customization.

_Uses `buildah` to create a container image leveraging link:https://konflux-ci.dev/architecture/ADR/0036-trusted-artifacts.html[trusted artifacts]. It also optionally creates a source image and runs some build-time tests. Information is shared between tasks using OCI artifacts instead of link:https://kubernetes.io/docs/concepts/storage/persistent-volumes[Persistent Volume Claims]. EC will pass the link:https://conforma.dev/docs/ec-policies/release_policy.html#trusted_task__trusted[trusted_task.trusted] policy if all data used to build the artifact is generated from trusted tasks. (link:https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta?tab=tags[quay.io link], link:https://github.com/konflux-ci/build-definitions/blob/main/pipelines/docker-build-oci-ta/README.md[parameter documentation])_

==== _docker-build-multi-platform-oci-ta_ [[docker-build-multi-platform-oci-ta]]
This pipeline is ideal for building multi-arch container images from a Containerfile while maintaining trust after pipeline customization.

_Uses `buildah` to create a multi-platform container image leveraging link:https://konflux-ci.dev/architecture/ADR/0036-trusted-artifacts.html[trusted artifacts]. It also optionally creates a source images and runs some build-time tests. This pipeline requires that the link:https://github.com/konflux-ci/multi-platform-controller[multi platform controller] is deployed and configured on your {ProductName} instance. Information is shared between tasks using OCI artifacts instead of link:https://kubernetes.io/docs/concepts/storage/persistent-volumes[Persistent Volume Claims]. EC will pass the link:https://conforma.dev/docs/ec-policies/release_policy.html#trusted_task__trusted[trusted_task.trusted] policy if all data used to build the artifact is generated from trusted tasks. (link:https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta?tab=tags[quay.io link], link:https://github.com/konflux-ci/build-definitions/blob/main/pipelines/docker-build-multi-platform-oci-ta/README.md[parameter documentation])_

==== _fbc-builder_ [[fbc-builder]]

This pipeline is ideal for building and verifying xref:end-to-end:building-olm.adoc#building-the-file-based-catalog[file-based catalogs].

_Uses `buildah` to create a container image. Its build-time tests are limited to verifying the included catalog and not to scanning the image itself. (link:https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-fbc-builder?tab=tags[quay.io link], link:https://github.com/konflux-ci/build-definitions/blob/main/pipelines/fbc-builder/README.md[parameter documentation])_

==== _tekton-bundle-builder-oci-ta_ [[tekton-bundle-builder-oci-ta]]

This pipeline is ideal for building Tekton tasks as bundles.

_Uses `tkn-bundle-oci-ta` task to create tekton task bundles and push them as oci-artifacts to a repository.
Information is shared between tasks using OCI artifacts instead of link:https://kubernetes.io/docs/concepts/storage/persistent-volumes[Persistent Volume Claims]. Conforma will pass the link:https://conforma.dev/docs/ec-policies/release_policy.html#trusted_task__trusted[trusted_task.trusted] policy if all data used to build the artifact is generated from trusted tasks. (link:https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder-oci-ta?tab=tags[quay.io link], link:https://github.com/konflux-ci/build-definitions/blob/main/pipelines/tekton-bundle-builder-oci-ta/README.md[parameter documentation])_
