= Creating a release plan

A ReleasePlan (RP) CR is created for a specific Application. It defines the the process to release a specific Application Snapshot in a target tenant namespace, whether automatic releases are enabled, as well as additional data to pass to a corresponding RPA.

== Creating a `ReleasePlan` object

The development team creates a `ReleasePlan` object in the developer tenant namespace. The `ReleasePlan` object includes a reference to the application that the development team wants to release, along with tenant namespace where the application is supposed to be released.

.*Prerequisites*

* You have an existing Development tenant namespace.
* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started in the CLI] page.

.*Procedures*

. Create a `ReleasePlan.yaml` object locally.

+
*Example `ReleasePlan.yaml` object*

+
[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
 labels:
   release.appstudio.openshift.io/auto-release: 'true' <.>
   release.appstudio.openshift.io/standing-attribution: 'true'
   release.appstudio.openshift.io/releasePlanAdmission: 'rpa-name' <.>
 name: sre-production <.>
 namespace: dev-tenant-namespace <.>
spec:
 application: <application-name> <.>
 data: <key> <.>
 pipelineRef: <pipeline-ref> <.>
 serviceAccount: <service-account> <.>
 releaseGracePeriodDays: <days> <.>
 target: managed-tenant-namespace <.>
----

+
<.> Optional: Control if Releases should be created automatically for this ReleasePlan when tests pass. Defaults to true.
<.> Optional: The name of the RPA to use if more than one RPA references the specified application.
<.> The name of the release plan.
<.> The development team's tenant namespace.
<.> The name of the application that you want to deploy to the managed tenant namespace.
<.> Optional: An unstructured key used for providing data for the managed Pipeline.
<.> Optional: Reference to the Pipeline to be executed by the release service.
<.> Optional: The name of the service account to use in the Pipeline to gain elevated privileges. It's used only if you have defined the `pipelineRef` value.
<.> Optional: The number of days a Release should be kept before being garbage collected. (default is 7 days)
<.> The tenant namespace to which the system deploys the application. This tenant namespace is created by the Managed environment team (for example, your organization's SRE team)

. In the development tenant namespace, apply the `ReleasePlan.yaml` file and add the resource to your cluster by running the following command:

+
[source,shell]
----
$ kubectl apply -f ReleasePlan.yaml -n dev
----

.*Verification*

. In the {ProductName} UI, select the *Release services* > *Release plan* tab.
. Review the Release plan object that you just added. Using the Release plan tab, you can update or delete the selected Release plan object.
. When a ReleasePlan is correctly configured to be paired with a ReleasePlanAdmission, its *Status* will display as being `Matched`.
