= Creating a release
:description: Creating a Release CR to promote a snapshot through an approved ReleasePlan.

A `Release` object informs Konflux that an Application's
xref:testing:page$integration/snapshots/index.adoc[Snapshot] is ready to be released, in accordiance
with its associated xref:create-release-plan.adoc[ReleasePlan].

== Creating a `Release` object

The development team creates a `Release` object in the developer tenant namespace. The `Release` object includes a reference to the application snapshot that the development team wants to release, along with release plan that will be used to release the application.

.*Prerequisites*

* You have an existing Development tenant namespace.
* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started in the CLI] page.
* You have completed the steps for creating a ReleasePlanAdmission and a matching ReleasePlan.

.*Procedures*

. Create a `Release.yaml` object locally.

+
include::releasing:partial$example-manual-release.adoc[]

. In the development tenant namespace, create the `Release` object using the `kubectl` command line:
+
[source,shell]
----
$ kubectl create -f Release.yaml
----

.*Verification*

. In the {ProductName} UI, select the *Applications* tab
. Click on the application that is being released
. Click on the *Releases* tab
. See the recent releases that have been created for the application.
. You can find a link to the release pipeline run by clicking on the name of the release that you created.
