= Creating a release plan admission

A ReleasePlanAdmission (RPA) CR exists within a managed tenant namespace. It defines the specific pipeline to run and a given xref:compliance:index.adoc[Conforma] Policy which needs to pass for the Snapshot before that pipeline can proceed.

When an application is ready for release, the Development team contacts the owners of the managed tenant namespace (for example, their organization's SRE team) and  requests access to the managed tenant namespace. A RPA object is then created in the managed tenant namespace to specify the configuration.

== Creating a `ReleasePlanAdmission` object

.*Prerequisites*

* An existing Development and Managed tenant namespace.
* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started in the CLI] page.
* An existing `ReleasePlan` object in the Development tenant namespace.

.*Procedures*

. Create a `ReleasePlanAdmission.yaml` object locally.

+
*Example `ReleasePlanAdmission.yaml` object*

+
[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
 labels:
   release.appstudio.openshift.io/auto-release: 'true' <.>
 name: sre-production <.>
 namespace: managed-tenant-namespace <.>
spec:
 applications:
  - demo-app <.>
 data: <key> <.>
 environment: <sre-production> <.>
 origin: <dev-tenant-namespace> <.>
 pipelineRef: <pipeline_ref> <.>
 policy: <policy> <.>
 serviceAccount: <service-account> <.>

----

+
<.> Optional: Control whether or not this ReleasePlanAdmission is entirely disabled. If set to false, attempted releases will fail with a validation error. Defaults to true.
<.> The name of the release plan admission.
<.> The Managed environment team's tenant namespace.
<.> A list of applications that you want to enable to be deployed in the managed tenant namespace.
<.> Optional: An unstructured key used for providing data for the managed Pipeline.
<.> Optional: The environment from which the application updates are allowed to be received in the Managed tenant namespace. This environment is created by the Development team.
<.> The development team tenant namespace where the application is defined.
<.> Reference to the Pipeline to be executed by the release service.
<.> The enterprise contract policy against which the system validates an application before releasing it to production.
<.> Optional: The name of the service account to use in the Pipeline to gain elevated privileges. It's used only if you have defined the `pipelineRef` value.

+
NOTE: The  ReleasePlanAdmission.yaml represents the reciprocal link to the ReleasePlan.yaml objects created by the development team.

. In the Managed tenant namespace, apply the `ReleasePlanAdmission.yaml` file and add the resource to your cluster by running the following command:

+
[source,shell]
----
kubectl apply -f ReleasePlanAdmission.yaml -n managed
----

.*Verification*

. In the {ProductName} UI, select the *Release services* > *Release plan admission* tab.
. Review the RPA object that you just added. Using the Release plan admission tab, you can update or delete the selected Release plan admission object.
. When a ReleasePlanAdmission is correctly configured to be paired with a ReleasePlan, its *Status* will display as being `Matched`.
