= Re-trigger a release manually
:description: Re-triggering a release by creating a new Release CR with the same spec.

`Release` objects create workloads with a finite lifecycle. Once created, a `Release` object's `spec` field cannot be modified.
To "re-trigger" a release, create a new instance of the desired `Release` object using the same values in the `spec` field.


WARNING: Creating multiple `Release` objects for the same snapshot can result in duplicate actions taken during the release process.
Consult with the team managing the release pipeline before creating a new `Release` object for a given snapshot.

.*Procedures*

. Create a new `Release.yaml` object locally, using similar values to the original `Release` object.

.. Use `kubectl` to obtain the data of an existing `Release` object:
+
[source,shell]
----
$ kubectl get release <release-name> -n <dev-tenant-namespace> -o yaml > Release.yaml
----

.. Alternatively, use https://github.com/itaysk/kubectl-neat[kubectl-neat] to remove unnecessary fields from the `Release` object:
+
[source,shell]
----
$ kubectl neat get release <release-name> -n <dev-tenant-namespace> -o yaml > Release.yaml
----

. Remove the following fields from the `Release.yaml` object:
.. `metadata` fields:
... `annotations`
... `creationTimestamp`
... `finalizers`
... `generation`
... `name`
... `ownerReferences`
... `resourceVersion`
... `uid`
.. `status` - remove entirely or set its value to `{}`

. Verify that the `Release.yaml` object is valid:
+
include::releasing:partial$example-manual-release.adoc[]

. Create the new `Release` object using the data in `Release.yaml`:
+
[source,shell]
----
$ kubectl create -f Release.yaml
----

.*Verification*

. In the {ProductName} UI, select the *Applications* tab
. Click the released application
. Click the *Releases* tab
. View the recent releases created for the application
. Click the name of the release to view the results of its release pipeline

