= Creating applications and components

At the time of publication, to create applications in {ProductName}, you need to manually configure them by editing YAML files. This might change, in favor of maintaining those configurations in the {ProductName} UI.

.Prerequisites:

* xref:/advanced-how-tos/installing/enabling-builds.adoc[Enabled] build pipelines for your instance of {ProductName}.
* The following values from your {ProductName} GitHub App:
** The private key
** The App ID
** The webhook secret
* A GitHub repository with source code for your application 
** It must have the same basic structure as our example repository
* Read/write access to the repository for your instance of {ProductName} 
* link:https://kubernetes.io/docs/tasks/tools/[kubectl] CLI tool

.Procedure:

. In the GitHub repository for your application, install your organization’s {ProductName} GitHub App.
. In the repository for your instance of {ProductName}, prepare an `application-and-component.yaml` file for your namespace. 
.. If your namespace does not already have this YAML file, create it with the following path: `/test/resources/demo-users/user/<namespace>/application-and-component.yaml`. Use the namespace 2 file as a template.
.. Replace the two `url` values in that YAML file as follows:
... For the `url` value beneath `git`, provide the URL that you would use to locally clone your application’s repository. This URL ends with `.git`.
... For the `url` value beneath `spec`, at the end of the file, provide the URL for your application’s repository that you see in your browser, without `.git` at the end.
+
NOTE: To add other components to the same namespace, reference the example YAML file beneath this procedure. 
. Login to the Kubernetes cluster where Konflux is deployed. 
. Run the following command. Be sure to replace <namespace> with your actual namespace.
+
`kubectl create -f /test/resources/demo-users/user/<namespace>/application-and-component.yaml`
. Run the following command. But first, be sure to export as variables or hard code the values for `PATH_PRIVATE_KEY`, `APP_ID`, and `WEBHOOK_SECRET`.
+
[source]
--
kubectl -n pipelines-as-code create secret generic pipelines-as-code-secret \
       --from-literal github-private-key="$(cat $PATH_PRIVATE_KEY)" \
       --from-literal github-application-id="APP_ID" \
       --from-literal webhook.secret="WEBHOOK_SECRET"
--
. Still in the context of your {ProductName} repository, run `kubectl create -f smee/smee-client`.
. Now, you can trigger your application’s first build pipeline. In the git repository for your application, using your preferred text editor, open a pull request against the `/.tekton/pull-request.yaml` file. 
.. Specifically, replace any existing value for the `git-url` field with the git URL for your application’s repository. (This is the URL you would use to clone the repository locally; it ends with `.git`.)
. Once the PR is made, a build pipeline should start. You can track its progress on GitHub, or in the {ProductName} UI. If the pipeline is successful, you can merge the PR.

== Example YAML file for multiple components

If you want to create an application that contains multiple components, model your `application-and-component.yaml` file after the following example.

[source]
--
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: user-ns2
  annotations:
    application.thumbnail: "1"
spec:
  displayName: test-application
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: test-component1
  namespace: user-ns2
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
spec:
  application: test-application
  componentName: test-component1
  source:
    git:
      revision: main
      url: https://github.com/konflux-ci/testrepo.git
      dockerfileUrl: Dockerfile
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: test-component2
  namespace: user-ns2
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
spec:
  application: test-application
  componentName: test-component2
  source:
    git:
      revision: main
      url: https://github.com/konflux-ci/anothertestrepo.git
      dockerfileUrl: Dockerfile
      context: ./
---
apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: project-repository-testrepo
  namespace: user-ns2
spec:
  url: "https://github.com/konflux-ci/testrepo"
---
apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: project-repository-anothertestrepo
  namespace: user-ns2
spec:
  url: "https://github.com/konflux-ci/anothertestrepo"
--
