= Creating applications and components

To create an application in {ProductName}, someone must enable build pipelines in your instance of {ProductName}. This includes creating a GitHub application, so {ProductName} can access users' pull requests, and configuring a smee channel, to listen for those PRs. The first procedure in this document explains how to perform these tasks. 

Once build pipelines are enabled, users can create their applications in {ProductName}. The second procedure below describes how to create a single-component application. For applications with multiple components...
//Yftach: This is basically the question I had: What would users do to create an app with multiple components? Add a new URL to the same application-and-component.yaml? Create a new YAML file in the same namespace, within the Konflux directory?

== Enabling build pipelines for your instance of {ProductName}:

.Prerequisites:

* Install link:https://github.com/konflux-ci/konflux-ci/tree/main[{ProductName}]
* Read/write access to your {ProductName} instance’s repository

.Procedure:

. Create a GitHub app according to link:https://pipelinesascode.com/docs/install/github_apps/#manual-setup[these Pipelines as Code instructions].
. Start a new link:https://smee.io/[smee] channel.
. In the repository for your instance of {ProductName}, edit the file /smee/smee-client.yaml. Replace <smee-channel> with the webhook proxy URL from the previous step. 

== Creating your applications and components with {ProductName}:

.Prerequisites:

* link:https://kubernetes.io/docs/tasks/tools/[kubectl] CLI tool
* The following values from your {ProductName} GitHub application:
** The private key
** The application ID
** The webhook secret
* A GitHub repository with source code for your application 
** It must have the same basic structure as our example repository
* Read/write access to the repository for your instance of {ProductName} 

.Procedure:

. In the GitHub repository for your application, install your organization’s {ProductName} GitHub application.
. In the repository for your instance of {ProductName}, you need to replace two `url` values in the relevant YAML file for your namespace. The path for this file is `/test/resources/demo-users/user/<namespace>/application-and-component.yaml`. Replace the two `url` values as follows:
.. For the `url` value beneath `git`, provide the URL that you would use to locally clone your application’s repository. This URL ends with `.git`.
.. For the `url` value beneath `spec`, at the end of the file, provide the URL for your application’s repository that you see in your browser, without `.git` at the end. 
. Login to {ProductName} xref:../getting-started/cli.adoc[through your CLI]. 
. Run the following command. Be sure to replace <namespace> with your actual namespace.
+
`kubectl create -f /test/resources/demo-users/user/<namespace>/application-and-component.yaml`
. Run the following command. But first, be sure to export as variables or hard code the values for `PATH_PRIVATE_KEY`, `APP_ID`, and `WEBHOOK_SECRET`.
+
[source]
--
kubectl -n pipelines-as-code create secret generic pipelines-as-code-secret \
       --from-literal github-private-key="$(cat $PATH_PRIVATE_KEY)" \
       --from-literal github-application-id="APP_ID" \
       --from-literal webhook.secret="WEBHOOK_SECRET"
--
. Still in the context of your {ProductName} repository, run `kubectl create -f smee/smee-client`.
. Now, you can trigger your application’s first build pipeline. In the git repository for your application, using your preferred text editor, open a pull request against the `/.tekton/pull-request.yaml` file. 
.. Specifically, replace any existing value for the `git-url` field with the git URL for your application’s repository. (This is the URL you would use to clone the repository locally; it ends with `.git`.)
. Once the PR is made, a build pipeline should start. You can track its progress on GitHub, or in the {ProductName} UI. If the pipeline is successful, you can merge the PR.
