= Inspecting artifact attestations

Generally speaking, link:https://github.com/in-toto/attestation/blob/main/spec/README.md#in-toto-attestation-framework-spec[attestations] are authenticated metadata about software artifacts. An identity (and their private cryptographic key) are required to create an attestation for a software artifact. The primary attestation that {ProductName} generates is the SLSA provenance which is produced by link:https://tekton.dev/docs/concepts/supply-chain-security/[Tekton Chains]. This provenance contains information from the PipelineRun that generated the attested artifact including input parameters for the Tasks as well as Task results.

After you have found the image for a xref:/how-tos/creating.adoc#finding-the-built-image[recently completed build pipeline] and exported the value to the `IMAGE` environment variable, you are ready to start exploring the information stored in the attestations.

== Inspect the SLSA provenance

Tekton Chains produces a very detailed SLSA provenance. The output from the following provenance is over 2800 lines long!

[source]
--
$ cosign download attestation $IMAGE | jq -r '.payload | @base64d | fromjson' | head
{
  "_type": "https://in-toto.io/Statement/v0.1",
  "predicateType": "https://slsa.dev/provenance/v0.2",
  "subject": [
    {
      "name": "quay.io/redhat-user-workloads/rhtap-integration-tenant/oras-container/oras-container",
      "digest": {
        "sha256": "5d0a8a5535fcc4ba467264cacbdeab2fb8662a538a61cb7fc8b3155e3f20fa39"
      }
    },
--

Therefore, it will likely be convenient to use tools like `jq` to further filter the provenance to identify smaller sets of relevant information.

=== Identify the build parameters

Since the SLSA provenance includes metadata about the input parameters, we can use it to view the parameters for the Tekton PipelineRun including its source repository!

[source]
--
$ cosign download attestation $IMAGE | jq -r '.payload | @base64d | fromjson | .predicate.invocation.parameters'
{
  "build-args-file": "",
  "build-source-image": "false",
  "dockerfile": "Containerfile",
  "git-url": "https://github.com/konflux-ci/oras-container",
  "hermetic": "false",
  "image-expires-after": "",
  "java": "false",
  "output-image": "quay.io/redhat-user-workloads/rhtap-integration-tenant/oras-container/oras-container:477ee20f7e6d146ea203c4aaa0507f4d1e925a53",
  "path-context": ".",
  "prefetch-input": "",
  "rebuild": "false",
  "revision": "477ee20f7e6d146ea203c4aaa0507f4d1e925a53",
  "skip-checks": "false"
}
--

.Prerequisites

* xref:/getting-started/cli.adoc[Login] to {ProductName} in your CLI 
* link:https://stedolan.github.io/jq/download/[Install] the `jq` command line utility 
* link:https://docs.sigstore.dev/cosign/installation/[Install] the `cosign` command line utility

.Procedure

First you need to get the image path for the component whose attestation you want to download. Then, you can use `cosign` to download the provenance. 

. List your components: 

+
[source]
--
oc get components
--

+
Example output:
+
[source]
--
NAME                         AGE   STATUS   REASON   TYPE
partner-catalog-build-ucmg   24d   True     OK       Updated
partner-catalog-ec-pz7b      18d   True     OK       Updated
--

. Choose a component and get its image path: 
+
[source]
--
oc get component <component name> -ojson | jq '.status.containerImage'
--

+
Example:
+
[source]
--
oc get component partner-catalog-build-ucmg -ojson | jq '.status.containerImage'
--

. For convenience, save the image path to a local variable.
+
Example:
+
[source]
--
IMAGE=quay.io/redhat-user-workloads/rhn-support-csears-tenant/demo-build/partner-catalog-build-ucmg@sha256:<output omitted>
--


. Use `cosign` to download the attestation, and use `jq` to put it in a human-readable format: 
+
[source]
--
cosign download attestation $IMAGE | jq '.payload|@base64d|fromjson'
--

+
Example output:
+
[source]
--
{
  "_type": "https://in-toto.io/Statement/v0.1",
  "predicateType": "https://slsa.dev/provenance/v0.2",
  "subject": [
    {
      "name": "quay.io/redhat-user-workloads/rhn-support-csears-tenant/demo-build/partner-catalog-build-ucmg",
      "digest": {
        "sha256": "<output omitted>"
      }
    }
  ],
  "predicate": {
    "builder": {
      "id": "https://tekton.dev/chains/v2"
    },
    "buildType": "tekton.dev/v1beta1/TaskRun",
    "invocation": {
<remaining output omitted>
--

. Use the same tools to download the attestation signature:

+
[source]
--
cosign download attestation $IMAGE | jq '.|keys'
--

+
Example output:
+
[source]
--
[
  "payload",
  "payloadType",
  "signatures"
]
--

+
. (Optional) You can also print a high-level overview of the provenance-related artifacts that {ProductName} has created for a component: 

+
[source]
--
cosign tree $IMAGE
--
+
Example output:
+
[source]
--
📦 Supply Chain Security Related artifacts for an image: quay.io/redhat-user-workloads/rhn-support-csears-tenant/demo-build/partner-catalog-build-ucmg@sha256::<output omitted>
└── 💾 Attestations for an image tag: quay.io/redhat-user-workloads/rhn-support-csears-tenant/demo-build/partner-catalog-build-ucmg:sha256-:<output omitted>.att
   ├── 🍒 sha256::<output omitted>
└── 🔐 Signatures for an image tag: quay.io/redhat-user-workloads/rhn-support-csears-tenant/demo-build/partner-catalog-build-ucmg:sha256-:<output omitted>.sig
 └── 🍒 sha256::<output omitted>
└── 📦 SBOMs for an image tag: quay.io/redhat-user-workloads/rhn-support-csears-tenant/demo-build/partner-catalog-build-ucmg:sha256-:<output omitted>.sbom
  └── 🍒 sha256:<output omitted>
--

== Inspecting the downloaded provenance

The generated provenance includes information from the Tekton PipelineRun that generated the attested artifact. It 

== Additional resources
* Learn about the SLSA framework and xref:/index.adoc#supply-chain-security-through-slsa-conformity[how {ProductName} meets the requirements of SLSA Build Level 3].
* Red Hat's Enterprise Contract (EC) is a powerful tool that you can also use to verify your SLSA provenance; visit link:https://enterprisecontract.dev/docs/user-guide/main/cli.html#_validating_an_image[this page]  to learn how to use the EC CLI tool to verify your provenance. You will need the public key used by Tekton Chains, which you can find by following link:https://enterprisecontract.dev/docs/user-guide/main/cli.html#_finding_the_public_key[these instructions].
