= Editing integration tests

Once you have xref:./adding.adoc[added] an Integration Test Scenario to {ProductName}, you may want to change the configurations for it. 

.Prerequisites

* You have xref:./adding.adoc[added an integration test] in {ProductName}.

.Procedure

Complete the following steps in the {ProductName} console:

. Open an existing application and go to the *Integration tests* tab.

. Select the three dots on the right side of the table.

. Select the *Edit* action.

. Make any changes to the test that are needed

    * Modify the *GitHub URL* if you need to specify a different repository.
    * Modify the *Revision* if you need to use a different branch, tag, or commit in the repository.
    * Modify the *Path in repository* to point to a new location for the `.yaml` file.
    * Add or remove *Parameters* which are passed to the integration test scenario.
    * Modify whether this integration test scenario is required or optional for release.

+
NOTE: A failing integration test marks the application snapshot as failed. A failing required test will prevent the automated release. If you have selected *Mark as optional for release*, a failure in this test will still result in an automated release of the application snapshot.

. Select *Save changes*.

. To start building a new component (and afterwards trigger a new integration test), either open a new pull request (PR) that targets the tracked branch of a component in the application, or comment '/retest' on an existing PR.

== Configuring the enterprise contract policy

All applications created in {ProductName} will have one integration test scenario to enable xref:/advanced-how-tos/managing-compliance-with-ec[manage compliance with Enterprise Contract] by default. You can configure your tests to use a customized link:https://enterprisecontract.dev/docs/user-guide/custom-config.html#_using_an_enterprisecontractpolicy_kubernetes_custom_resource_cr[Kubernetes Custom Resource] policy on the cluster.

.Procedure

Complete the following steps in the {ProductName} console:

. Open an existing application and go to the *Integration tests* tab.

. Select the three dots on the right side of the table.

. Select the *Edit* action.

. Click on *Add parameter*.

    * In *Name*, write `POLICY_CONFIGURATION`
    * In *Value*, write the namespace and CR name for the policy, `<namespace>/<policy-name>`

. Click on *Save changes*.

. To start building a new component (and afterwards trigger a new integration test), either open a new pull request (PR) that targets the tracked branch of a component in the application, or comment '/retest' on an existing PR.

.Verification

When the new build is finished:

. Go to the *Integration tests* tab and select the highlighted name of your test.

. Go to the *Pipeline runs* tab of that test and select the most recent run.

.  On the *Details* page, you can see if the test succeeded for that component. The policy used by the test should be updated. 
