== PipelineRuns are left in Pending

Pipeline runs might be stuck in "pending" status because a requested resource is not available.

- Check the status of the workload's Pipeline (should have the same name as the PipelineRun) and look for a message similar to "not found resource".

For example, when using a not available VM-flavor for certain cluster (or non-existent or invalid format[1]) like linux-c2xlarge/arm64, you would find a message similar to this:
"resource linux-c2xlarge/arm64 is not found"

The available VM flavors can be found listed in https://konflux.pages.redhat.com/docs/users/getting-started/multi-platform-builds.html.
As some of those VM flavos might not been defined in every cluster, you can confirm in https://github.com/redhat-appstudio/infra-deployments/tree/main/components/multi-platform-controller, navigating to the folder of the cluster you using and then checking the host-values.yaml file that the VM flavor is in the dynamicConfigs section
In any case you could request to Konflux Infrastructure adding a certain flavor to a Cluster

[1] If the platform "flavor" name/string contains invalid characters like not alphanumeric characters, - or _ along other combinations considered invalid, the PipelineRun will end with "resource key validation failed"