== PipelineRuns stuck in a Pending state

A PipelineRun might get stuck in a 'Pending' status because a requested resource is not available.

To diagnose this issue, check the status of the workload's Pipeline, which should have the same name as the PipelineRun. Look for a message similar to `resource <VM_TYPE> unavailable in ClusterQueue'`like this:

....
status:
  conditions:
  - lastTransitionTime: "2026-01-21T17:25:41Z"
    message: 'couldn''t assign flavors to pod set pod-set-1: resource <VM_TYPE>
      unavailable in ClusterQueue'
    observedGeneration: 1
    reason: Pending
    status: "False"
    type: QuotaReserved
  resourceRequests:
  - name: pod-set-1
    resources:
      <VM_TYPE>: "1"
      tekton.dev/pipelineruns: "1"


For example, using an unavailable, non-existent, or invalid format[1] VM flavor for a cluster, such as `linux-c2xlarge/arm64`, results in a message similar to this:
....

.Procedure: Verifying available VM flavors
. For a list of available VM flavors, see the link:https://konflux.pages.redhat.com/docs/users/getting-started/multi-platform-builds.html[multi-platform builds documentation].
. Because some of these VM flavors might not be defined in every cluster, you can confirm their availability:
.. Navigate to the link:https://github.com/redhat-appstudio/infra-deployments/tree/main/components/multi-platform-controller[`infra-deployments` repository].
.. Go to the folder for your cluster.
.. In the `host-values.yaml` file, check that the VM flavor is in the `dynamicConfigs` section.

If a flavor is not available, you can request that the Konflux Infrastructure team adding it to a cluster.

[1] If the platform `flavor` name contains invalid characters (any characters other than alphanumeric, `-`, or `_`), the PipelineRun fails with a `resource key validation failed` error.
