= Enabling build pipelines

Before users can create an application in {ProductName}, you must enable build pipelines in your instance of {ProductName}. At the time of publication, this process includes configuring a smee channel, to listen for users' pull requests, and creating a GitHub App, so {ProductName} can access those PRs. 

.Prerequisites:

* Install link:https://github.com/konflux-ci/konflux-ci/tree/main[{ProductName}]
* Read/write access to your {ProductName} instance’s repository

.Procedure:

. Start a new link:https://smee.io/[smee] channel.
. In the repository for your instance of {ProductName}, edit the file /smee/smee-client.yaml. Replace `<smee-channel>` with the webhook proxy URL from the previous step. 
. Create a GitHub App according to link:https://pipelinesascode.com/docs/install/github_apps/#manual-setup[these Pipelines as Code instructions]. For the *Webhook URL* field, use the webhook proxy URL for your smee channel.

.Verification

* To verify that you successfully enabled build pipelines, a user should try to xref:/how-tos/creating.adoc[create an application].