= Tenant Release Pipelines

The usual release process in {ProductName} involves two different teams: a *Development team* and a *Managed environment team* as described in
xref:/releasing/index.adoc[Releasing an application]. But, sometimes the Development team wants to release their software to some destination that is directly under their control, using their own secrets, without depending on a Managed environment team. In {ProductName} we call this model a *tenant release pipeline*. It's a release pipeline that runs in the tenant namespace of the Development team, rather than in that of the Managed environment team.

The gist here is that you are going to follow the regular instructions to xref:/releasing/create-release-plan.adoc[create a ReleasePlan], but you will omit the `target` and specify the `pipeline` directly on your `ReleasePlan`.


.*Prerequisites*

* You have an existing Development workspace.
* You have completed the steps listed in the xref:/getting-started/index.adoc#getting-started-with-the-cli[Getting started in the CLI] page.
* Either choose one of the link:https://github.com/konflux-ci/release-service-catalog[konflux release pipelines], or write your own.

NOTE: If you write a good reusable release pipeline, please submit it to our link:https://github.com/konflux-ci/release-service-catalog[catalog] so others can use it.

.Procedure

. Create a `ReleasePlan.yaml` object locally.

+
*Example `ReleasePlan.yaml` object*

+
[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
 labels:
   release.appstudio.openshift.io/auto-release: 'true' <.>
   release.appstudio.openshift.io/standing-attribution: 'true'
 name: publish <.>
 namespace: dev-workspace <.>
spec:
 application: <application-name> <.>
 data:
   mapping:
     components: <.>
       - name: demo-component-1
         repository: registry/destination-image-repository-1
         tags: [latest]
       - name: demo-component-2
         repository: registry/destination-image-repository-2
         tags: [latest]
 tenantPipeline:
   pipelineRef: <.>
     resolver: git
     params:
       - name: url
         value: "https://github.com/<your-github-user>/<your-pipeline-repo>.git"
       - name: revision
         value: main
       - name: pathInRepo
         value: "<path-to-your-pipeline>"
   serviceAccountName: appstudio-pipeline <.>
----

+
<.> Optional: Control if Releases should be created automatically for this ReleasePlan when tests pass. Defaults to true.
<.> The name of the release plan.
<.> The development team's workspace.
<.> The name of the application that you want to release via a pipeline in the development workspace.
<.> A list containing the destination repository for each component
<.> Reference to the Pipeline to be executed in the development workspace.
<.> The name of the service account used to execute the tenant pipeline.

. In the Development workspace, apply the `ReleasePlan.yaml` file and add the resource to your cluster by running the following command:

+
[source,shell]
----
kubectl apply -f ReleasePlan.yaml -n dev
----

. Provision any secrets needed by the particular release pipeline you chose and xref:/building/creating-secrets.adoc[upload them to the Development workspace].

. Create an `rbac.yaml` file locally. Note: This is optional, as your tenant pipeline doesn't necessarily need to get any Releases, Snapshots, or ReleasePlans. However, the operator does pass references to these CRs to the tenant release pipeline and it is a common use case to use details from them in your pipeline.

+
*Example `rbac.yaml` object*

+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: publish-role <.>
 namespace: dev-workspace <.>
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releases
  - releaseplans
  - snapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releases/status
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: publish-rolebinding <.>
 namespace: dev-workspace <.>
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: publish-role <.>
subjects:
- kind: ServiceAccount
  name: appstudio-pipeline <.>
  namespace: dev-workspace <.>
----

+
<.> The name of the Role.
<.> The development team's workspace.
<.> The name of the RoleBinding.
<.> The development team's workspace.
<.> The name of the Role from (1).
<.> The name of the service account used to execute the tenant pipeline.
<.> The development team's workspace.

. In the Development workspace, apply the `rbac.yaml` file and add the resources to your cluster by running the following command:

+
[source,shell]
----
kubectl apply -f rbac.yaml -n dev-workspace
----

.Next steps

* *Create a `release` object:* The development team creates a Release object to reference a specific Snapshot and ReleasePlan. It indicates the users' intent to release that Snapshot via the tenant release pipeline defined in the ReleasePlan.
