[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component <.>
metadata:
  name: <component-name>
  namespace: <namespace>
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"<name-of-the-pipeline-to-use>","bundle":"latest"}' <.>
    git-provider: gitlab <.>
    git-provider-url: https://gitlab.com <.>
spec:
  application: <owning-application-name> <.>
  componentName: <component-name>
  source:
    git:
      url: https://gitlab.com/your-org/your-repo.git <.>
      revision: main <.>
      context: ./ <.>
      dockerfileUrl: Containerfile <.>
  containerImage: <oci-repository-to-push-image-to> <.>
----
<.> A component is required to map to a git repository to build.
<.> Optional: If used, it should point to a xref:installing:enabling-builds.adoc#customize-pipelines[configured pipeline]. If not specified, the default configured pipeline will be used.
<.> Use the `gitlab` value.
<.> Configure with the provider URL.
<.> Each component belongs to _one_ application. That application should be defined in the same file if it does not already exist.
<.> URL for the source repository. This MUST use the `https://[...]` format for cloning a repository.
<.> Optional: Branch to build in the repository. If not specified, the default branch will be used.
<.> Optional: The context to build within the git repository. If not specified, the default defined in the configured pipeline will be used.
<.> Optional: Path to the Containerfile within the context. If not specified, the default value of "Dockerfile" will be used.
<.> Optional: If the xref:installing:enabling-builds.adoc#enable-image-controller[image controller] is not deployed, this is required. You must create a xref:building:secrets/index.adoc#creating-registry-pull-secrets[registry secret] that has permissions to push and pull for the specified path. If an ImageRepository is created, this should be omitted.
