=== CI/CD Automation

{ProductName} simplifies your DevOps processes through:

* *Automated Pipelines*: {ProductName} provides default pipeline configurations for building, testing, and deploying production software. You can trigger these pipelines via Git events, such as when team members accept push or pull requests. {ProductName} posts the results back to your source control management system.

* *Integration with GitHub and GitLab*: {ProductName} allows you to integrate your build processes into GitHub or GitLab. This integration uses the Tekton framework to run pipelines in your Konflux cluster. We will add more source control management providers in the future.

* *Red Hat Subscription Support*: {ProductName} allows you to integrate subscription content into your pipeline to build software that uses these RPMs as dependencies.

=== Collaboration

{ProductName} encourages you to collaborate with its open-source community through resources such as its link:https://github.com/konflux-ci/community[community] and link:https://github.com/konflux-ci[overview pages] on GitHub.

=== Customization and Flexibility

{ProductName} allows you to customize your project to meet your specific requirements, maintain high security standards, and adapt to various enterprise needs. {ProductName}'s adaptable platform ensures compliance without sacrificing flexibility.

=== Open Source

The core components of {ProductName} are distributed under the Apache 2.0 license and built on top of Kubernetes and OpenShift. You can set {ProductName} up locally or as a cloud-native platform for your development teams. {ProductName} utilizes standard command-line tools, such as Kubernetes' `kubectl` and OpenShift's `oc`, for managing resources.

=== Robust Software Supply Chain Security

{ProductName} offers unparalleled transparency into your software's build process, helping you address vulnerabilities before they become issues. {ProductName} emphasizes robust security through the following mechanisms:

* *Hermetic Builds:* {ProductName} supports using hermetic builds to isolate your build processes from changes to the host system to ensure consistency and produce accurate Software Bills of Materials (SBOMs) for tracking components, dependencies, and so forth.

* *SLSA Compliance*: {ProductName} supports level three Supply Chain Levels for Software Artifacts (SLSAs) reference.footnote:[link:https://slsa.dev[SLSA] is a security framework created through industry collaboration. We use this framework as a guide to reinforce the build process we use for your applications, thereby enhancing the security of your software supply chain. To see how we meet the requirements set out by SLSA, see xref:metadata:index.adoc#supply-chain-security-through-slsa-conformity[Supply chain security through SLSA conformity].], allowing you to generate secure, detailed records for each build step to ensure transparency and trust in your software supply chain.

* *Stringent Access Controls*: {ProductName} allows you to implement policies using native Kubernetes features like Role-Based Access Control (RBAC) and tenant namespaces to safeguard your sensitive data and ensure access compliance without giving up flexibility.

* *Vulnerability Detection*: {ProductName} automatically scans for critical vulnerabilities every time you submit a pull request and verifies your container images against custom rules and secure frameworks.

=== Testing and Deployment

{ProductName} provides the following features to facilitate testing and deploying your software:

* *Build Once, Deploy Anywhere*: {ProductName} optimizes your release process for multiple deployments without redundancy, which reduces your time-to-market

* *Integration Testing*: {ProductName} runs your integration tests for complex applications and displays the results in your source control management system.

* *Supports Multiple Architectures*: {ProductName} supports architectures like *amd64* and *arm64*, offering you flexibility when targeting diverse deployment environments.
