= Creating secrets for your builds

For the build service to access external resources, such as source code repositories, you need to create secrets that store the necessary credentials.
You can use the `oc` command to manually create secrets for source code management tools such as GitHub or GitLab.
For example, to create a secret for the gitlab.com holding a personal access token, use the following secret format:

[source, yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: pipelines-as-code-secret
  namespace: <YOUR NAMESPACE>
  labels:
    appstudio.redhat.com/credentials: scm
    appstudio.redhat.com/scm.host: <gitlab-host> # eg. gitlab.cee.redhat.com
type: kubernetes.io/basic-auth
stringData:
  password: <PERSONAL ACCESS TOKEN>
----

[NOTE]
====
Using the PAT authentication requires only the `password` key. The `username` should not be set.
If you will set both `username` and `password` keys, the authentication type will be considered as `basic`, so
basic auth client will be created using those credentials, which may not work (or considered as deprecated login method)
with some SCM providers.
====

This secret will be used by build service to perform both "Simple" and "Pipeline-as-Code" builds.