= Creating task input secrets

Sometimes to run the tasks properly, you may need to pass secrets to these tasks. Consult the documentation for these tasks to understand the proper specification of the secrets required, for example the required keys/values.

NOTE: One such task is the link:https://github.com/konflux-ci/build-definitions/tree/main/task/sast-snyk-check[sast-snyk-check] task that uses the third-party service link:https://snyk.io/[snyk] to perform static application security testing (SAST) as a part of the default {ProductName} pipeline. Use this procedure to upload your snyk.io token. Name the secret `snyk-secret` and use the key `snyk_token` so that the snyk task in the {ProductName} pipeline will be able to access and use the token.

.Procedure

. In {ProductName}, from the left navigation menu, select **Secrets**.
. From the **Secrets** page, click **Add secret**.
. For **Secret type**, select **Key/value secret**
. For **Secret name**, enter a unique name for your secret.
. Under **Key/value secret**, expand **Key/value 1**, then enter a key.
. For **Upload the file with value for your key or paste its contents**, do one of the following:
    * Click **Upload** to browse to, select, and upload the file that contains your key value.
    * Drag the file that contains your key value into the space under **Upload**.
    * Paste the contents of the file that contains your key value into the space under **Upload**.
  Click **Clear** to remove the contents of the space under **Upload**.
. Optional: Click **Add another key/value**.
. Optional: Under **Labels**, add a label to tag or provide more context for your secret.
. Click **Add secret**.

== Notable task input secrets

* xref:building:activation-keys-subscription.adoc#adding-activation-keys-to-the-tenant-namespace[activation-key]
* xref:building:prefetching-dependencies.adoc#creating-the-netrc-secret[netrc]
* xref:testing:build/snyk.adoc[snyk-secret]
* xref:testing:integration/third-parties/testing-farm.adoc[testing-farm-secret]
