= Creating registry pull secrets

Some container builds may use parent images from registries that require authentication, for example, `registry.redhat.io`. Until these credentials have been configured, the builds will continue to fail due to the system being unable to pull the required images.

.Procedure

. Obtain the username and password login credentials for the container registry.
    * For access to `registry.redhat.io`, you can create a registry service account at https://access.redhat.com/terms-based-registry/accounts.
. In the correct {ProductName} tenant namespace, go to **Secrets**.
. Click **Add secret**.
. For **Secret type**, select **Image pull secret**.
. For **Authentication type**, select **Image registry credentials**.
. For **Registry server address** enter the image registry (for example `registry.redhat.io`).
. Enter the username for the registry in **Username**.
. Enter the password for the registry in **Password**.
. Click **Add secret**.

== Example of creating a quay.io secret

. Login to {ProductName} console your tenant namespace
. Click on `Secrets` on the left menu.
. Click on `Add Secret`
. Choose `Image pull secret` for `Secret type`
. Enter `Secret name` , for example `my-quay-secret`
. From `Link secret options` select either `All existing and future components in the namespace` or
  `Select components in the namespace` and specify components
. Choose `Image registry credentials` in `Authentication type` field
. Enter `quay.io/repository_full_path` in `Registry server address` (specify full repository path, eg. quay.io/test_organization/test-repository)
. Enter your Quay.io username in `Username`
. Enter your Quay.io API token in `Password` field.
. Click on `Add secret`
. Email is optional


Here is the YAML representation of the secret (for reference):

[source,yaml]
----
apiVersion: v1
data:
.dockerconfigjson: <base64-encoded-credentials>
kind: Secret
metadata:
name: my-quay-secret
namespace: <your-tenant>
type: kubernetes.io/dockerconfigjson
----


[NOTE]
====
* **Secret Linking via UI**
  The {ProductName} UI links image pull secrets to either selected or all components
    specific service accounts `build-pipeline-$COMPONENT_NAME`
  - No pipeline YAML changes are required.
  - Tasks like the buildah task will use this secret automatically when pulling images from `quay.io`. For details, see the link:https://github.com/konflux-ci/build-definitions/tree/main/task/buildah-oci-ta/[buildah-oci-ta task documentation].

* **Manual Secret Creation**
  . **Link Secret To SA**
    - If you create the secret manually (e.g., via `kubectl` or YAML), you must **manually link it**
      to the component specific `build-pipeline-$COMPONENT_NAME` ServiceAccount in your namespace.
    - If you want to manually create shared secret which will be then linked to all newly
      onboarded component specific ServiceAccounts,
      add to the secret label: **build.appstudio.openshift.io/common-secret: 'true'**.
      It is the same as what UI is doing when selecting Link secret option with
      All existing and future components in the namespace.

  . **Secrets Via Tenant Namespace**
    - Explicitly mount secrets as files using a tenant namespace
    - RBAC: Ensure the ServiceAccount has permission to access the secret (via Role/RoleBinding).

  . **Secrets as Environment Variables**
    - Inject secrets into environment variables
    - RBAC: The ServiceAccount must have `get` permission for the secret.

* **Troubleshooting**
  For issues with secret linking, review the xref:troubleshooting:registries.adoc#check-if-the-secret-is-linked-to-the-service-account[troubleshooting section].
====
