= Creating secrets for your builds

When you build your pipeline, you might want to add tasks that require **secrets** in order to access external resources.

Secrets can be categorized depending on when they need to be added.

. Before a component is added. If a secret is needed to access the source control platform like xref:building:secrets/index.adoc#creating-source-control-secrets[GitLab], you must create a secret before you create the component.
. Before a build succeeds. Some artifact build tasks need specific secrets to be able to pull all of the content to include in the final artifact. For example, you can add secrets for xref:building:secrets/creating-registry-pull-secrets.adoc[container registries] after you create the component but they must be provided before a successful build can occur.
. After a component has been onboarded. These secrets are often used in tasks. The tasks included in the {ProductName} pipelines will not fail if a secret is not created properly. Instead, the task will just not run the code like with xref:building:secrets/creating-task-input-secrets.adoc[snyk].

== Creating task input secrets

Task input secrets are key/value secrets that provide credentials or tokens to specific pipeline tasks. These secrets are optional and only needed for tasks that interact with external services.

For detailed instructions on creating task input secrets, see xref:building:secrets/creating-task-input-secrets.adoc[Creating task input secrets].

== Creating registry pull secrets

Registry pull secrets (image pull secrets) allow your builds to authenticate with private container registries when pulling base images or parent images.

For detailed instructions on creating registry pull secrets, see xref:building:secrets/creating-registry-pull-secrets.adoc[Creating registry pull secrets].

[#scm-secrets]
== Creating source control management secrets

Some source control providers require authentication secrets before onboarding components. See xref:building:secrets/creating-scm-secrets.adoc[Creating source control management secrets] for detailed instructions.

== Referencing Secrets in a Containerfile

Sometimes you might need to reference a secret directly in your Containerfile. For example, if your build uses cryptographic parameters stored in secrets, you can use the `ADDITIONAL_SECRET` parameter to customize encryption in your Containerfile. For details, see the link:https://github.com/konflux-ci/build-definitions/tree/main/task/buildah-oci-ta/[buildah-oci-ta task documentation].

.Procedure

. Create the secret (see xref:building:secrets/creating-task-input-secrets.adoc[Creating task input secrets]). In this example, we create a secret with SALT and KEY_HASH keys:
+
[subs="+quotes",yaml]
----
kind: Secret
apiVersion: v1
metadata:
  name: _<your_secret_name>_
  namespace: _<your_workspace_tenant>_
data:
  SALT: 11111111111
  KEY_HASH: 11111111111
type: Opaque
----

. In the build-container task of your Tekton pipeline, set the value of the `ADDITIONAL_SECRET` parameter to _<your_secret_name>_:
+
[subs="+quotes",yaml]
----
# ...
  tasks:
    - name: build-container
      params:
        - name: ADDITIONAL_SECRET
          value: _<your_secret_name>_
# ...
----

. In the Containerfile, use a `RUN` command to mount the secret. In this example, we export the content of the mounted files as environment variables for `cargo build`:
+
[subs="+quotes",dockerfile]
----
# Build with secrets
RUN --mount=type=secret,id=_<your_secret_name>_/SALT \
    --mount=type=secret,id=_<your_secret_name>_/KEY_HASH \
    export SALT="$(cat /run/secrets/_<your_secret_name>_/SALT)" && \
    export KEY_HASH="$(cat /run/secrets/_<your_secret_name>_/KEY_HASH)" && \
    cargo build --release
----

[NOTE]
====
Only `RUN` commands are able to reference secrets.
====

include::partial${context}-secrets-external-vault.adoc[]

== Additional resources

* To configure push secrets for your Build and Release pipelines, see link:https://github.com/konflux-ci/konflux-ci?tab=readme-ov-file#configuring-a-push-secret-for-the-build-pipeline[Configuring push secrets] in the Konflux GitHub repository.
