= Creating secrets for your builds

When you build your pipeline, you might want to add tasks that require **secrets** in order to access external resources.

Secrets can be categorized depending on when they need to be added.

. Before a component is added. If a secret is needed to access the source control platform like xref:building:secrets/creating-scm-secrets.adoc[GitLab], you must create a secret before you create the component.
. Before a build succeeds. Some artifact build tasks need specific secrets to be able to pull all of the content to include in the final artifact. For example, you can add secrets for xref:building:secrets/creating-registry-pull-secrets.adoc[container registries] after you create the component but they must be provided before a successful build can occur.
. After a component has been onboarded. These secrets are often used in tasks. The tasks included in the {ProductName} pipelines will not fail if a secret is not created properly. Instead, the task will just not run the code like with xref:building:secrets/creating-task-input-secrets.adoc[snyk].

== Creating task input secrets

Task input secrets are key/value secrets that provide credentials or tokens to specific pipeline tasks. These secrets are optional and only needed for tasks that interact with external services.

For detailed instructions on creating task input secrets, see xref:building:secrets/creating-task-input-secrets.adoc[Creating task input secrets].

== Creating registry pull secrets

Registry pull secrets (image pull secrets) allow your builds to authenticate with private container registries when pulling base images or parent images.

For detailed instructions on creating registry pull secrets, see xref:building:secrets/creating-registry-pull-secrets.adoc[Creating registry pull secrets].

[#scm-secrets]
== Creating source control management secrets

Some source control providers require authentication secrets before onboarding components. See xref:building:secrets/creating-scm-secrets.adoc[Creating source control management secrets] for detailed instructions.

== Referencing Secrets in a Containerfile

You can mount secrets directly in your Containerfile using the `ADDITIONAL_SECRET` parameter and Buildah secret mounts. This is useful for build-time secrets like cryptographic keys or credentials.

For detailed instructions on referencing secrets in a Containerfile, see xref:building:secrets/referencing-secrets-in-containerfile.adoc[Referencing Secrets in a Containerfile].

== Secrets from external vaults

You can integrate Konflux with external vault solutions to manage secrets centrally.

For more information, see xref:building:secrets/secrets-from-external-vaults.adoc[Secrets from external vaults].

== Additional resources

* To configure push secrets for your Build and Release pipelines, see link:https://github.com/konflux-ci/konflux-ci?tab=readme-ov-file#configuring-a-push-secret-for-the-build-pipeline[Configuring push secrets] in the Konflux GitHub repository.
