= Creating secrets for your builds

When you build your pipeline, you might want to add tasks that require **secrets** in order to access external resources.

Secrets can be categorized depending on when they need to be added.

. Before a component is added. If a secret is needed to access the source control platform like xref:building:secrets/index.adoc#creating-source-control-secrets[GitLab], you must create a secret before you create the component.
. Before a build succeeds. Some artifact build tasks need specific secrets to be able to pull all of the content to include in the final artifact. For example, you can add secrets for xref:building:secrets/index.adoc#creating-registry-pull-secrets[container registries] after you create the component but they must be provided before a successful build can occur.
. After a component has been onboarded. These secrets are often used in tasks. The tasks included in the {ProductName} pipelines will not fail if a secret is not created properly. Instead, the task will just not run the code like with xref:building:secrets/creating-task-input-secrets.adoc[snyk].

== Creating task input secrets

Task input secrets are key/value secrets that provide credentials or tokens to specific pipeline tasks. These secrets are optional and only needed for tasks that interact with external services.

For detailed instructions on creating task input secrets, see xref:building:secrets/creating-task-input-secrets.adoc[Creating task input secrets].

[#creating-registry-pull-secrets]
== Creating registry pull secrets

Some container builds may use parent images from registries that require authentication, for example, `registry.redhat.io`. Until these credentials have been configured, the builds will continue to fail due to the system being unable to pull the required images.

.Procedure

. Obtain the username and password login credentials for the container registry.
    * For access to `registry.redhat.io`, you can create a registry service account at https://access.redhat.com/terms-based-registry/accounts.
. In the correct {ProductName} tenant namespace, go to **Secrets**. 
. Click **Add secret**.  
. For **Secret type**, select **Image pull secret**.
. For **Authentication type**, select **Image registry credentials**.
. For **Registry server address** enter the image registry (for example `registry.redhat.io`).
. Enter the username for the registry in **Username**.
. Enter the password for the registry in **Password**.
. Click **Add secret**.

=== Example of creating a quay.io secret

. Login to {ProductName} console your tenant namespace
. Click on `Secrets` on the left menu.
. Click on `Add Secret`
. Choose `Image pull secret` for `Secret type`
. Enter `Secret name` , for example `my-quay-secret`
. From `Link secret options` select either `All existing and future components in the namespace` or
  `Select components in the namespace` and specify components
. Choose `Image registry credentials` in `Authentication type` field
. Enter `quay.io/repository_full_path` in `Registry server address` (specify full repository path, eg. quay.io/test_organization/test-repository)
. Enter your Quay.io username in `Username`
. Enter your Quay.io API token in `Password` field.
. Click on `Add secret`
. Email is optional


Here is the YAML representation of the secret (for reference):

[source,yaml]
----
apiVersion: v1
data:
.dockerconfigjson: <base64-encoded-credentials>
kind: Secret
metadata:
name: my-quay-secret
namespace: <your-tenant>
type: kubernetes.io/dockerconfigjson
----


[NOTE]
====
* **Secret Linking via UI**
  The {ProductName} UI links image pull secrets to either selected or all components
    specific service accounts `build-pipeline-$COMPONENT_NAME`
  - No pipeline YAML changes are required.
  - Tasks like the buildah task will use this secret automatically when pulling images from `quay.io`. For details, see the link:https://github.com/konflux-ci/build-definitions/tree/main/task/buildah-oci-ta/[buildah-oci-ta task documentation].

* **Manual Secret Creation**
  . **Link Secret To SA**
    - If you create the secret manually (e.g., via `kubectl` or YAML), you must **manually link it**
      to the component specific `build-pipeline-$COMPONENT_NAME` ServiceAccount in your namespace.
    - If you want to manually create shared secret which will be then linked to all newly
      onboarded component specific ServiceAccounts,
      add to the secret label: **build.appstudio.openshift.io/common-secret: 'true'**.
      It is the same as what UI is doing when selecting Link secret option with
      All existing and future components in the namespace.

  . **Secrets Via Tenant Namespace**
    - Explicitly mount secrets as files using a tenant namespace
    - RBAC: Ensure the ServiceAccount has permission to access the secret (via Role/RoleBinding).

  . **Secrets as Environment Variables**
    - Inject secrets into environment variables
    - RBAC: The ServiceAccount must have `get` permission for the secret.

* **Troubleshooting**
  For issues with secret linking, review the xref:troubleshooting:registries.adoc#check-if-the-secret-is-linked-to-the-service-account[troubleshooting section].
====

[#scm-secrets]
== Creating source control management secrets

Some source control providers require authentication secrets before onboarding components. See xref:building:secrets/creating-scm-secrets.adoc[Creating source control management secrets] for detailed instructions.

== Referencing Secrets in a Containerfile

Sometimes you might need to reference a secret directly in your Containerfile. For example, if your build uses cryptographic parameters stored in secrets, you can use the `ADDITIONAL_SECRET` parameter to customize encryption in your Containerfile. For details, see the link:https://github.com/konflux-ci/build-definitions/tree/main/task/buildah-oci-ta/[buildah-oci-ta task documentation].

.Procedure

. Create the secret (see xref:building:secrets/creating-task-input-secrets.adoc[Creating task input secrets]). In this example, we create a secret with SALT and KEY_HASH keys:
+
[subs="+quotes",yaml]
----
kind: Secret
apiVersion: v1
metadata:
  name: _<your_secret_name>_
  namespace: _<your_workspace_tenant>_
data:
  SALT: 11111111111
  KEY_HASH: 11111111111
type: Opaque
----

. In the build-container task of your Tekton pipeline, set the value of the `ADDITIONAL_SECRET` parameter to _<your_secret_name>_:
+
[subs="+quotes",yaml]
----
# ...
  tasks:
    - name: build-container
      params:
        - name: ADDITIONAL_SECRET
          value: _<your_secret_name>_
# ...
----

. In the Containerfile, use a `RUN` command to mount the secret. In this example, we export the content of the mounted files as environment variables for `cargo build`:
+
[subs="+quotes",dockerfile]
----
# Build with secrets
RUN --mount=type=secret,id=_<your_secret_name>_/SALT \
    --mount=type=secret,id=_<your_secret_name>_/KEY_HASH \
    export SALT="$(cat /run/secrets/_<your_secret_name>_/SALT)" && \
    export KEY_HASH="$(cat /run/secrets/_<your_secret_name>_/KEY_HASH)" && \
    cargo build --release
----

[NOTE]
====
Only `RUN` commands are able to reference secrets.
====

include::partial${context}-secrets-external-vault.adoc[]

== Additional resources

* To configure push secrets for your Build and Release pipelines, see link:https://github.com/konflux-ci/konflux-ci?tab=readme-ov-file#configuring-a-push-secret-for-the-build-pipeline[Configuring push secrets] in the Konflux GitHub repository.
