= Referencing Secrets in a Containerfile

Sometimes you might need to reference a secret directly in your Containerfile. For example, if your build uses cryptographic parameters stored in secrets, you can use the `ADDITIONAL_SECRET` parameter to customize encryption in your Containerfile. For details, see the link:https://github.com/konflux-ci/build-definitions/tree/main/task/buildah-oci-ta/[buildah-oci-ta task documentation].

.Procedure

. Create the secret (see xref:building:secrets/creating-task-input-secrets.adoc[Creating task input secrets]). In this example, we create a secret with SALT and KEY_HASH keys:
+
[subs="+quotes",yaml]
----
kind: Secret
apiVersion: v1
metadata:
  name: _<your_secret_name>_
  namespace: _<your_workspace_tenant>_
data:
  SALT: 11111111111
  KEY_HASH: 11111111111
type: Opaque
----

. In the build-container task of your Tekton pipeline, set the value of the `ADDITIONAL_SECRET` parameter to _<your_secret_name>_:
+
[subs="+quotes",yaml]
----
# ...
  tasks:
    - name: build-container
      params:
        - name: ADDITIONAL_SECRET
          value: _<your_secret_name>_
# ...
----

. In the Containerfile, use a `RUN` command to mount the secret. In this example, we export the content of the mounted files as environment variables for `cargo build`:
+
[subs="+quotes",dockerfile]
----
# Build with secrets
RUN --mount=type=secret,id=_<your_secret_name>_/SALT \
    --mount=type=secret,id=_<your_secret_name>_/KEY_HASH \
    export SALT="$(cat /run/secrets/_<your_secret_name>_/SALT)" && \
    export KEY_HASH="$(cat /run/secrets/_<your_secret_name>_/KEY_HASH)" && \
    cargo build --release
----

[NOTE]
====
Only `RUN` commands are able to reference secrets.
====
