name: Linters
on:
  pull_request:
  merge_group:
    types: [checks_requested]
jobs:
  vale:
    name: vale
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get file changes
      
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor
      
      - name: Get changed files
        id: changed-files
        run: |
          # Get changed .adoc files and format as comma-separated list
          FILES=$(git diff --name-only --diff-filter=d origin/${{ github.base_ref }} | grep '\.adoc$' | paste -sd "," - || true)
          if [ -n "$FILES" ]; then
            echo "files=$FILES" >> "$GITHUB_OUTPUT"
            echo "any_changed=true" >> "$GITHUB_OUTPUT"
            echo "The following files will be checked against vale: $FILES"
          else
            echo "any_changed=false" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Vale Linter
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: errata-ai/vale-action@reviewdog
        with:
          vale_flags: "--minAlertLevel=error"
          files: ${{ steps.changed-files.outputs.files }}
          fail_on_error: true
          reporter: github-pr-check
          separator: ","
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}